/*
        프로그램명 : ins_TB_OR_OC_GLACC_GL계정
        타켓테이블 : TB_OR_OC_GLACC
        최조작성자 : 박승윤
*/
DECLARE
        P_BASEDAY   VARCHAR2(8);   -- 기준일자
        P_LSS_GRP_C VARCHAR2(40);  -- 손실회계계정코드(G/L 계정 코드명)
        P_LD_CN    NUMBER;  -- 로딩건수

BEGIN
		--P_BASEDAY := '20220706';
        SELECT TO_CHAR(SYSDATE-1,'YYYYMMDD') 
          INTO P_BASEDAY
          FROM DUAL;
  			
        DBMS_OUTPUT.PUT_LINE('기준일 : '||P_BASEDAY);
        
        P_LSS_GRP_C := 'LSS_ACG_ACCC';
        DBMS_OUTPUT.PUT_LINE('손실회계계정코드(G/L 계정 코드명) : '||P_LSS_GRP_C);
        
        /*계정내용 UPDATE*/
        MERGE INTO OPEOWN.TB_OR_OM_CODE A
             USING DWZOWN.TB_SOR_FSI_ACSB_BC B
                ON (A.INTG_GRP_C = TRIM(P_LSS_GRP_C) AND TRIM(A.IDVDC_VAL) = TRIM(B.ACSB_CD))
  	    WHEN MATCHED THEN UPDATE SET A.INTG_IDVD_CNM = TRIM(B.ACSB_NM),A.RMK_CNTN = TRIM(B.ACSB_DESC);
        
  	    P_LD_CN := SQL%ROWCOUNT;
  	    DBMS_OUTPUT.PUT_LINE('손실회계계정코드 내용 UPDATE(TB_OR_OM_CODE) '||P_LD_CN); 
  	     
        DELETE FROM OPEOWN.TB_OR_OC_GLACC WHERE ACG_PRC_DT = TRIM(P_BASEDAY);
  	    
        INSERT INTO OPEOWN.TB_OR_OC_GLACC 
              (GRP_ORG_C,ACG_PRC_DT,BRC,LSS_ACG_ACCC,TR_SQNO,SACCT_SQNO,RVPY_DSC,CRC_CAN_DSC,ACC_SBJNM,
      		   ACC_AM,TR_CNTN,LSS_RG_STSC,LSS_RG_RQR_STSC,LSS_RG_RQR_DT,X_RSNCTT,FIR_INP_DTM,FIR_INPMN_ENO,LSCHG_DTM,LS_WKR_ENO)
		SELECT GRP_ORG_C,ACG_PRC_DT,BRC,LSS_ACG_ACCC,ROWNUM TR_SQNO,SACCT_SQNO,RVPY_DSC,CRC_CAN_DSC,ACC_SBJNM,
      		   ACC_AM,TR_CNTN,LSS_RG_STSC,LSS_RG_RQR_STSC,LSS_RG_RQR_DT,X_RSNCTT,FIR_INP_DTM,FIR_INPMN_ENO,LSCHG_DTM,LS_WKR_ENO
		  FROM
		     (
				SELECT DISTINCT 
				 NVL((SELECT GRP_ORG_C FROM OPEOWN.TB_OR_OM_GRPORG WHERE GRP_ORGNM  ='수협은행'),'01') GRP_ORG_C --그룹기관코드
				,TRIM(B.FSC_DT) ACG_PRC_DT
				,TRIM(B.BRNO) BRC
				,TRIM(B.ACSB_CD) LSS_ACG_ACCC
				,'0' SACCT_SQNO
				,'1' RVPY_DSC --입금
				,'0' CRC_CAN_DSC --정상
				,A.INTG_IDVD_CNM ACC_SBJNM
				,TRIM(B.ROM_AMT) ACC_AM--입금금액
				,TRIM(A.RMK_CNTN) TR_CNTN--거래내용
				,'' LSS_RG_STSC
				,'' LSS_RG_RQR_STSC
				,'' LSS_RG_RQR_DT
				,'' X_RSNCTT
				,SYSDATE FIR_INP_DTM
				,'SYSTEM' FIR_INPMN_ENO
				,SYSDATE LSCHG_DTM
				,'SYSTEM' LS_WKR_ENO
				FROM OPEOWN.TB_OR_OM_CODE A
				    ,DWZOWN.TB_SOR_GLM_CRDT_IS_BC B
				WHERE A.INTG_GRP_C = P_LSS_GRP_C
				  AND A.IDVDC_VAL = TRIM(B.ACSB_CD)
				  AND TRIM(B.FSC_DT) = TRIM(P_BASEDAY)
				  AND TRIM(B.ROM_CNT) <> '0' -- 입금건수
				UNION ALL
				SELECT DISTINCT 
				 NVL((SELECT GRP_ORG_C FROM OPEOWN.TB_OR_OM_GRPORG WHERE GRP_ORGNM  ='수협은행'),'01') GRP_ORG_C --그룹기관코드
				,TRIM(B.FSC_DT) ACG_PRC_DT
				,TRIM(B.BRNO) BRC
				,TRIM(B.ACSB_CD) LSS_ACG_ACCC
				,'0' SACCT_SQNO
				,'2' RVPY_DSC --지급
				,'0' CRC_CAN_DSC --정상
				,A.INTG_IDVD_CNM ACC_SBJNM
				,TRIM(B.DFRY_AMT) ACC_AM--지급금액
				,TRIM(A.RMK_CNTN) TR_CNTN--거래내용
				,'' LSS_RG_STSC
				,'' LSS_RG_RQR_STSC
				,'' LSS_RG_RQR_DT
				,'' X_RSNCTT
				,SYSDATE FIR_INP_DTM
				,'SYSTEM' FIR_INPMN_ENO
				,SYSDATE LSCHG_DTM
				,'SYSTEM' LS_WKR_ENO
				FROM OPEOWN.TB_OR_OM_CODE A
				    ,DWZOWN.TB_SOR_GLM_CRDT_IS_BC B
				WHERE A.INTG_GRP_C = P_LSS_GRP_C
				  AND A.IDVDC_VAL = TRIM(B.ACSB_CD)
				  AND TRIM(B.FSC_DT) = TRIM(P_BASEDAY)
				  AND TRIM(B.DFRY_CNT) <> '0' -- 지급건수
				UNION ALL
				SELECT DISTINCT 
				 NVL((SELECT GRP_ORG_C FROM OPEOWN.TB_OR_OM_GRPORG WHERE GRP_ORGNM  ='수협은행'),'01') GRP_ORG_C --그룹기관코드
				,TRIM(B.FSC_DT) ACG_PRC_DT
				,TRIM(B.BRNO) BRC
				,TRIM(B.ACSB_CD) LSS_ACG_ACCC
				,'0' SACCT_SQNO
				,'1' RVPY_DSC --입금
				,'3' CRC_CAN_DSC --취소
				,A.INTG_IDVD_CNM ACC_SBJNMs
				,TRIM(B.ROM_AMT) ACC_AM--취소입금금액
				,TRIM(A.RMK_CNTN) TR_CNTN--거래내용
				,'' LSS_RG_STSC
				,'' LSS_RG_RQR_STSC
				,'' LSS_RG_RQR_DT
				,'' X_RSNCTT
				,SYSDATE FIR_INP_DTM
				,'SYSTEM' FIR_INPMN_ENO
				,SYSDATE LSCHG_DTM
				,'SYSTEM' LS_WKR_ENO
				FROM OPEOWN.TB_OR_OM_CODE A
				    ,DWZOWN.TB_SOR_GLM_CRDT_IS_BC B
				WHERE A.INTG_GRP_C = P_LSS_GRP_C
				  AND A.IDVDC_VAL = TRIM(B.ACSB_CD)
				  AND TRIM(B.FSC_DT) = TRIM(P_BASEDAY)
				  AND TRIM(B.CNCL_ROM_CNT) <> '0' -- 취소입금건수
				UNION ALL
				SELECT DISTINCT 
				 NVL((SELECT GRP_ORG_C FROM OPEOWN.TB_OR_OM_GRPORG WHERE GRP_ORGNM  ='수협은행'),'01') GRP_ORG_C --그룹기관코드
				,TRIM(B.FSC_DT) ACG_PRC_DT
				,TRIM(B.BRNO) BRC
				,TRIM(B.ACSB_CD) LSS_ACG_ACCC
				,'0' SACCT_SQNO
				,'2' RVPY_DSC --지급
				,'3' CRC_CAN_DSC --취소
				,A.INTG_IDVD_CNM ACC_SBJNM
				,TRIM(B.CNCL_DFRY_AMT) ACC_AM--취소지급금액
				,TRIM(A.RMK_CNTN) TR_CNTN--거래내용
				,'' LSS_RG_STSC
				,'' LSS_RG_RQR_STSC
				,'' LSS_RG_RQR_DT
				,'' X_RSNCTT
				,SYSDATE FIR_INP_DTM
				,'SYSTEM' FIR_INPMN_ENO
				,SYSDATE LSCHG_DTM
				,'SYSTEM' LS_WKR_ENO
				FROM OPEOWN.TB_OR_OM_CODE A
				    ,DWZOWN.TB_SOR_GLM_CRDT_IS_BC B
				WHERE A.INTG_GRP_C = P_LSS_GRP_C
				  AND A.IDVDC_VAL = TRIM(B.ACSB_CD)
				  AND TRIM(B.FSC_DT) = TRIM(P_BASEDAY)
				  AND TRIM(B.CNCL_DFRY_CNT) <> '0' -- 취소지급건수
			 )
			 ;
        P_LD_CN := SQL%ROWCOUNT;
  	    DBMS_OUTPUT.PUT_LINE('손실회계계정코드 건수 INSERT(TB_OR_OC_GLACC) '||P_LD_CN); 
		COMMIT;
	
END
;
/
EXIT
