/*
        프로그램명 : ins_RCSA중요리스크선정
        타켓테이블 : OPEOWN.TB_OR_RH_KRK_SLT
        최조작성자 : 박승윤
*/
DECLARE

        P_LD_CN    NUMBER;  -- 로딩건수

BEGIN
	
			--1년 이내 연관 KRI RED 등급 발생
			MERGE INTO 
			OPEOWN.TB_OR_RH_KRK_SLT A
			USING
			(
			SELECT B.OPRK_RKP_ID,C.KRI_GRDNM
			 FROM OPEOWN.TB_OR_RH_REL_KRI A
			     ,OPEOWN.TB_OR_RM_RKP B
			     ,OPEOWN.TB_OR_KS_RKI_SMST C
			WHERE A.OPRK_RKP_ID = B.OPRK_RKP_ID
			  AND A.OPRK_RKI_ID = C.OPRK_RKI_ID
			  AND B.VLD_YN = 'Y'
			  AND C.KRI_GRDNM = 'RED'
			  AND TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YYYYMM')<=C.BAS_YM
			GROUP BY B.OPRK_RKP_ID,C.KRI_GRDNM
			) B
			  ON (A.OPRK_RKP_ID = B.OPRK_RKP_ID AND A.KRK_SLT_BASCD = '05')
			WHEN MATCHED THEN UPDATE SET A.KRK_SLT_ED_DT = TO_CHAR(SYSDATE,'YYYYMMDD'),LSCHG_DTM=SYSDATE
			WHEN NOT MATCHED THEN 
			INSERT (GRP_ORG_C,OPRK_RKP_ID,KRK_SLT_BASCD,KRK_SLT_ST_DT,KRK_SLT_ED_DT
			       ,FIR_INP_DTM,FIR_INPMN_ENO,LSCHG_DTM,LS_WKR_ENO)
			VALUES ('01',B.OPRK_RKP_ID,'05', TO_CHAR(SYSDATE,'YYYYMMDD'),TO_CHAR(SYSDATE,'YYYYMMDD')
			        ,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM')
			;

	 		P_LD_CN := SQL%ROWCOUNT;

            DBMS_OUTPUT.PUT_LINE(P_LD_CN || '건 1년 이내 연관 KRI RED 등급 발생');
	
            
            
            --1년 이내 연관 RCSA RED 등급 발생
			MERGE INTO 
			OPEOWN.TB_OR_RH_KRK_SLT A
			USING
			(
			SELECT B.OPRK_RKP_ID,C.RK_EVL_GRD_C
			 FROM OPEOWN.TB_OR_RM_RKP B
			     ,OPEOWN.TB_OR_RM_EVL C
			     ,OPEOWN.TB_OR_RH_EVL_DCZ D
			WHERE B.VLD_YN = 'Y'
			  AND B.OPRK_RKP_ID = C.OPRK_RKP_ID
			  AND C.OPRK_RKP_ID = D.OPRK_RKP_ID
			  AND C.BAS_YM = D.BAS_YM
			  AND C.BRC = D.BRC
			  AND C.DCZ_SQNO = D.DCZ_SQNO
			  AND D.RK_EVL_DCZ_STSC >=15
			  AND C.RK_EVL_GRD_C = '3'
			  AND TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YYYYMM')<=C.BAS_YM
			GROUP BY B.OPRK_RKP_ID,C.RK_EVL_GRD_C
			) B
			  ON (A.OPRK_RKP_ID = B.OPRK_RKP_ID AND A.KRK_SLT_BASCD = '04')
			WHEN MATCHED THEN UPDATE SET A.KRK_SLT_ED_DT = TO_CHAR(SYSDATE,'YYYYMMDD'),LSCHG_DTM=SYSDATE
			WHEN NOT MATCHED THEN 
			INSERT (GRP_ORG_C,OPRK_RKP_ID,KRK_SLT_BASCD,KRK_SLT_ST_DT,KRK_SLT_ED_DT
			       ,FIR_INP_DTM,FIR_INPMN_ENO,LSCHG_DTM,LS_WKR_ENO)
			VALUES ('01',B.OPRK_RKP_ID,'04', TO_CHAR(SYSDATE,'YYYYMMDD'),TO_CHAR(SYSDATE,'YYYYMMDD')
			        ,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM')  
			  
			  ;
		
			P_LD_CN := SQL%ROWCOUNT;

            DBMS_OUTPUT.PUT_LINE(P_LD_CN || '건 1년 이내 연관 RCSA RED 등급 발생');
            
			
			--3년 이내 손실사건 발생
			MERGE INTO 
			OPEOWN.TB_OR_RH_KRK_SLT A
			USING
			(
			SELECT B.OPRK_RKP_ID
			 FROM OPEOWN.TB_OR_RH_REL_LSS A
			     ,OPEOWN.TB_OR_RM_RKP B
			     ,OPEOWN.TB_OR_LM_LSHP C
			WHERE A.OPRK_RKP_ID = B.OPRK_RKP_ID
			  AND A.LSHP_AMNNO = C.LSHP_AMNNO
			  AND B.VLD_YN = 'Y'
			  AND TO_CHAR(ADD_MONTHS(SYSDATE,-36),'YYYYMMDD')<=C.OCU_DT
			GROUP BY B.OPRK_RKP_ID
			) B
			  ON (A.OPRK_RKP_ID = B.OPRK_RKP_ID AND A.KRK_SLT_BASCD = '03')
			WHEN MATCHED THEN UPDATE SET A.KRK_SLT_ED_DT = TO_CHAR(SYSDATE,'YYYYMMDD'),LSCHG_DTM=SYSDATE
			WHEN NOT MATCHED THEN 
			INSERT (GRP_ORG_C,OPRK_RKP_ID,KRK_SLT_BASCD,KRK_SLT_ST_DT,KRK_SLT_ED_DT
			       ,FIR_INP_DTM,FIR_INPMN_ENO,LSCHG_DTM,LS_WKR_ENO)
			VALUES ('01',B.OPRK_RKP_ID,'03', TO_CHAR(SYSDATE,'YYYYMMDD'),TO_CHAR(SYSDATE,'YYYYMMDD')
			        ,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM')
			;
 
			P_LD_CN := SQL%ROWCOUNT;

            DBMS_OUTPUT.PUT_LINE(P_LD_CN || '건 3년 이내 손실사건 발생');
END
;
/
EXIT