DROP PROCEDURE OPEETT.SP_DROP_TABLE;

CREATE OR REPLACE PROCEDURE OPEETT.SP_DROP_TABLE ( P_TABLE_NAME IN VARCHAR2)
AUTHID CURRENT_USER
AS
        notfoundtable EXCEPTION;
        resourcebusy  EXCEPTION;
        PRAGMA EXCEPTION_INIT(notfoundtable,-942);
        PRAGMA EXCEPTION_INIT(resourcebusy , -54);
BEGIN
        EXECUTE IMMEDIATE ('DROP TABLE '||P_TABLE_NAME||' PURGE');
        EXCEPTION
            WHEN notfoundtable THEN NULL;
            WHEN resourcebusy  THEN RAISE_APPLICATION_ERROR('-20004','Resource Busy Table Drop Fail  !!!!!!');
            WHEN OTHERS        THEN RAISE_APPLICATION_ERROR('-20005','Table Drop Fail  !!!!!!');
END;
/
GRANT EXECUTE ON OPEETT.SP_DROP_TABLE TO RL_OPE_EXE;
GRANT EXECUTE ON OPEETT.SP_DROP_TABLE TO PUBLIC;

EXIT
