create_own.bat TB_OR_BC_DZST_CFT.sql
create_own.bat TB_OR_BC_NARKDS.sql
create_own.bat TB_OR_BC_NARKHD.sql
create_own.bat TB_OR_BC_RKFCTR.sql
create_own.bat TB_OR_BC_RMRSK_GRD.sql
create_own.bat TB_OR_BH_BSNTP_EVL.sql
create_own.bat TB_OR_BH_BSNTP_WVAL.sql
create_own.bat TB_OR_BH_DZST_CFT_UGBR.sql
create_own.bat TB_OR_BH_IPTINF.sql
create_own.bat TB_OR_BH_NARK_SCR.sql
create_own.bat TB_OR_BH_NATV_RA.sql
create_own.bat TB_OR_BH_NED_BZDE.sql
create_own.bat TB_OR_BH_NED_HMRS.sql
create_own.bat TB_OR_BH_PALS_RLR.sql
create_own.bat TB_OR_BH_PRCD_BSN.sql
create_own.bat TB_OR_BH_RA.sql
create_own.bat TB_OR_BH_RADCZ.sql
create_own.bat TB_OR_BH_RA_FILE.sql
create_own.bat TB_OR_BH_RPT_DCZ.sql
create_own.bat TB_OR_BH_SSPIFN_EVL.sql
create_own.bat TB_OR_BH_SSPIFN_WVAL.sql
create_own.bat TB_OR_BM_BIAEVL.sql
create_own.bat TB_OR_BM_BIAEVL_DCZ.sql
create_own.bat TB_OR_BM_BSNTP.sql
create_own.bat TB_OR_BM_SSPIFN.sql
create_own.bat TB_OR_BM_UGBR_BKUP.sql
create_own.bat TB_OR_CF_ADM.sql
create_own.bat TB_OR_CF_ADM_DCZ.sql
create_own.bat TB_OR_CF_RPT.sql
create_own.bat TB_OR_CF_RPT_FILE.sql
create_own.bat TB_OR_FH_CPTAM.sql
create_own.bat TB_OR_FH_CPTAM_DCZ.sql
create_own.bat TB_OR_FH_INDEX.sql
create_own.bat TB_OR_FH_NVL.sql
create_own.bat TB_OR_FH_NVL_DCZ.sql
create_own.bat TB_OR_FH_REL_RKI.sql
create_own.bat TB_OR_FM_REPRKI.sql
create_own.bat TB_OR_GA_ACCAM.sql
create_own.bat TB_OR_GA_BIC.sql
create_own.bat TB_OR_GA_BICACC.sql
create_own.bat TB_OR_GA_BICDET.sql
create_own.bat TB_OR_GA_BYR_LMT.sql
create_own.bat TB_OR_GA_CISSTS_SMLT.sql
create_own.bat TB_OR_GA_FNASTM_DTL.sql
create_own.bat TB_OR_GA_FNASTM_UPDTL.sql
create_own.bat TB_OR_GA_FNASTM_UPLOAD.sql
create_own.bat TB_OR_GA_INLMT.sql
create_own.bat TB_OR_GA_INLMT_CASE.sql
create_own.bat TB_OR_GA_INLMT_RZT.sql
create_own.bat TB_OR_GA_LCDET.sql
create_own.bat TB_OR_GA_LCSUMM.sql
create_own.bat TB_OR_GA_LMT_EXRAT.sql
create_own.bat TB_OR_GA_MSRACC.sql
create_own.bat TB_OR_GA_MSRACCMM.sql
create_own.bat TB_OR_GA_MSRACC_HIST.sql
create_own.bat TB_OR_GA_MSRACC_TMP.sql
create_own.bat TB_OR_GA_MSRELM.sql
create_own.bat TB_OR_GA_MSRRZT.sql
create_own.bat TB_OR_GA_MSRRZT_DCZ.sql
create_own.bat TB_OR_GA_MSRRZT_SUB.sql
create_own.bat TB_OR_GA_TMP_ACC.sql
create_own.bat TB_OR_GA_UP_ACCAM.sql
create_own.bat TB_OR_KH_ACT_DCZ.sql
create_own.bat TB_OR_KH_BRC.sql
create_own.bat TB_OR_KH_HDNG.sql
create_own.bat TB_OR_KH_INF.sql
create_own.bat TB_OR_KH_LMT.sql
create_own.bat TB_OR_KH_MNTR_DCZ.sql
create_own.bat TB_OR_KH_NVL.sql
create_own.bat TB_OR_KH_NVL_DCZ.sql
create_own.bat TB_OR_KH_NVL_PSNZ.sql
create_own.bat TB_OR_KH_RKISLT.sql
create_own.bat TB_OR_KM_ACT.sql
create_own.bat TB_OR_KM_ACT_FILE.sql
create_own.bat TB_OR_KM_FIX_LMT.sql
create_own.bat TB_OR_KM_RKI.sql
create_own.bat TB_OR_KN_BRCMM.sql
create_own.bat TB_OR_KN_RKIMM.sql
create_own.bat TB_OR_KS_BR_SMST.sql
create_own.bat TB_OR_KS_RKI_BR_SMST.sql
create_own.bat TB_OR_KS_RKI_SMST.sql
create_own.bat TB_OR_LH_DCZ.sql
create_own.bat TB_OR_LH_LSAM.sql
create_own.bat TB_OR_LH_TRF.sql
create_own.bat TB_OR_LM_LSHP.sql
create_own.bat TB_OR_LM_OUT_LSHP.sql
create_own.bat TB_OR_LN_LSHP_HST.sql
create_own.bat TB_OR_OC_CAS.sql
create_own.bat TB_OR_OC_CTL.sql
create_own.bat TB_OR_OC_EMRK.sql
create_own.bat TB_OR_OC_GLACC.sql
create_own.bat TB_OR_OC_HPN.sql
create_own.bat TB_OR_OC_IFN.sql
create_own.bat TB_OR_OC_PRSS.sql
create_own.bat TB_OR_OH_EMAIL_DPAMN.sql
create_own.bat TB_OR_OH_EMAIL_FWDG.sql
create_own.bat TB_OR_OH_MENU_AUTH.sql
create_own.bat TB_OR_OH_MENU_PGM.sql
create_own.bat TB_OR_OH_MENU_PRSS.sql
create_own.bat TB_OR_OH_ORGZ_EMP.sql
create_own.bat TB_OR_OH_ORGZ_EMP_AUTH.sql
create_own.bat TB_OR_OH_PGM_AUTH.sql
create_own.bat TB_OR_OH_PRSS_AUTH.sql
create_own.bat TB_OR_OH_PRSS_UGBR.sql
create_own.bat TB_OR_OH_SVC_AUTH.sql
create_own.bat TB_OR_OM_AUTH.sql
create_own.bat TB_OR_OM_BLBD.sql
create_own.bat TB_OR_OM_BLBD_FILE.sql
create_own.bat TB_OR_OM_CODE.sql
create_own.bat TB_OR_OM_EMAIL.sql
create_own.bat TB_OR_OM_EMP.sql
create_own.bat TB_OR_OM_FQ.sql
create_own.bat TB_OR_OM_GRPORG.sql
create_own.bat TB_OR_OM_HLDY.sql
create_own.bat TB_OR_OM_MENU.sql
create_own.bat TB_OR_OM_OEA_BKUP.sql
create_own.bat TB_OR_OM_ONL_TRLOG.sql
create_own.bat TB_OR_OM_ORGZ.sql
create_own.bat TB_OR_OM_SCHD.sql
create_own.bat TB_OR_OM_SCHD_PLAN.sql
create_own.bat TB_OR_OM_SSO_INF.sql
create_own.bat TB_OR_ON_BIA_PRSSMM.sql
create_own.bat TB_OR_ON_BIA_PRSS_UGBRM.sql
create_own.bat TB_OR_ON_ORGZMM.sql
create_own.bat TB_OR_ON_PRSSMM.sql
create_own.bat TB_OR_ON_PRSS_UGBRMM.sql
create_own.bat TB_OR_ON_SNRO_ORGZMM.sql
create_own.bat TB_OR_RH_ACT_DCZ.sql
create_own.bat TB_OR_RH_BRC.sql
create_own.bat TB_OR_RH_CTL_SCF.sql
create_own.bat TB_OR_RH_EVL_DCZ.sql
create_own.bat TB_OR_RH_KRK_SLT.sql
create_own.bat TB_OR_RH_REL_KRI.sql
create_own.bat TB_OR_RH_REL_LSS.sql
create_own.bat TB_OR_RH_RKSLT.sql
create_own.bat TB_OR_RM_ACT.sql
create_own.bat TB_OR_RM_EVL.sql
create_own.bat TB_OR_RM_FRQ.sql
create_own.bat TB_OR_RM_GRD.sql
create_own.bat TB_OR_RM_NGRD.sql
create_own.bat TB_OR_RM_NGRD_CNTN.sql
create_own.bat TB_OR_RM_RKP.sql
create_own.bat TB_OR_RM_RPT.sql
create_own.bat TB_OR_RM_RPT_FILE.sql
create_own.bat TB_OR_RN_CTL_SCFMM.sql
create_own.bat TB_OR_RN_RKPMM.sql
create_own.bat TB_OR_RS_KRK.sql
create_own.bat TB_OR_RS_PRSS_GRD.sql
create_own.bat TB_OR_SH_CTEV.sql
create_own.bat TB_OR_SH_KRIRED.sql
create_own.bat TB_OR_SH_LSS.sql
create_own.bat TB_OR_SH_RCSA.sql
create_own.bat TB_OR_SH_RPTG_DCZ.sql
create_own.bat TB_OR_SH_RSKBSN.sql
create_own.bat TB_OR_SM_SCHD.sql