DROP TABLE OPEOWN.TB_OPE_KRI_磊陛技殴规瘤评02;

CREATE TABLE OPEOWN.TB_OPE_KRI_磊陛技殴规瘤评02
(
   STD_DT                                   VARCHAR2(8) NOT NULL
  ,CUST_NO                                 NUMBER(9)
  ,CUST_NTNT                               VARCHAR2(2)
) NOLOGGING;

COMMENT ON TABLE OPEOWN.TB_OPE_KRI_磊陛技殴规瘤评02               IS 'OPE_KRI_磊陛技殴规瘤评02';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_磊陛技殴规瘤评02.STD_DT       IS '扁霖老磊';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_磊陛技殴规瘤评02.CUST_NO      IS '绊按锅龋';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_磊陛技殴规瘤评02.CUST_NTNT    IS '绊按惫利';

GRANT SELECT ON TB_OPE_KRI_磊陛技殴规瘤评02 TO RL_OPE_ALL;
GRANT DELETE ON TB_OPE_KRI_磊陛技殴规瘤评02 TO RL_OPE_ALL;
GRANT UPDATE ON TB_OPE_KRI_磊陛技殴规瘤评02 TO RL_OPE_ALL;
GRANT INSERT ON TB_OPE_KRI_磊陛技殴规瘤评02 TO RL_OPE_ALL;
GRANT SELECT ON TB_OPE_KRI_磊陛技殴规瘤评02 TO RL_OPE_SEL;

EXIT
