-- OPEETT 계정으로 테이블 생성
DROP TABLE TB_OPE_KRI_TABLES;

CREATE TABLE TB_OPE_KRI_TABLES
(
    TABLE_NAME                             VARCHAR2(128)
   ,INF_TYPE                               VARCHAR2(20) 
) NOLOGGING;

GRANT SELECT ON TB_OPE_KRI_TABLES TO RL_OPE_ALL;
GRANT DELETE ON TB_OPE_KRI_TABLES TO RL_OPE_ALL;
GRANT UPDATE ON TB_OPE_KRI_TABLES TO RL_OPE_ALL;
GRANT INSERT ON TB_OPE_KRI_TABLES TO RL_OPE_ALL;
GRANT SELECT ON TB_OPE_KRI_TABLES TO RL_OPE_SEL;

EXIT
