DROP TABLE OPEOWN.TB_OPE_KRI_자금세탁방지팀03;

CREATE TABLE OPEOWN.TB_OPE_KRI_자금세탁방지팀03
(
   STD_DT                                   VARCHAR2(8) NOT NULL
  ,CUST_NTNT                                VARCHAR2(2)
  ,TR_AMT                                   NUMBER(20,4)  -- 거래금액
) NOLOGGING;

COMMENT ON TABLE OPEOWN.TB_OPE_KRI_자금세탁방지팀03               IS 'OPE_KRI_자금세탁방지팀03';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_자금세탁방지팀03.STD_DT       IS '기준일자';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_자금세탁방지팀03.CUST_NTNT    IS '고객국적';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_자금세탁방지팀03.TR_AMT       IS '거래금액';

GRANT SELECT ON TB_OPE_KRI_자금세탁방지팀03 TO RL_OPE_ALL;
GRANT DELETE ON TB_OPE_KRI_자금세탁방지팀03 TO RL_OPE_ALL;
GRANT UPDATE ON TB_OPE_KRI_자금세탁방지팀03 TO RL_OPE_ALL;
GRANT INSERT ON TB_OPE_KRI_자금세탁방지팀03 TO RL_OPE_ALL;
GRANT SELECT ON TB_OPE_KRI_자금세탁방지팀03 TO RL_OPE_SEL;

EXIT
