DROP TABLE OPEOWN.TB_OPE_KRI_여신팀02;

CREATE TABLE OPEOWN.TB_OPE_KRI_여신팀02
(
    STD_DT                                 VARCHAR2(8) NOT NULL
   ,VACN_NO                                VARCHAR2(14)    -- 가상계좌번호
   ,VACN_NO_US_CMPL_YN                     VARCHAR2(1)     -- 가상계좌번호사용완료여부
) NOLOGGING;

COMMENT ON TABLE OPEOWN.TB_OPE_KRI_여신팀02               IS 'OPE_KRI_여신팀02';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_여신팀02.STD_DT       IS '기준일자';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_여신팀02.VACN_NO                IS '가상계좌번호';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_여신팀02.VACN_NO_US_CMPL_YN     IS '가상계좌번호사용완료여부';

GRANT SELECT ON TB_OPE_KRI_여신팀02 TO RL_OPE_ALL;
GRANT DELETE ON TB_OPE_KRI_여신팀02 TO RL_OPE_ALL;
GRANT UPDATE ON TB_OPE_KRI_여신팀02 TO RL_OPE_ALL;
GRANT INSERT ON TB_OPE_KRI_여신팀02 TO RL_OPE_ALL;
GRANT SELECT ON TB_OPE_KRI_여신팀02 TO RL_OPE_SEL;

EXIT
