DROP TABLE OPEOWN.TB_OPE_KRI_정보보호팀03;

CREATE TABLE OPEOWN.TB_OPE_KRI_정보보호팀03
(
	 STD_DT                                   VARCHAR2(8)
  ,RULE_NM                                  VARCHAR2(100)
  ,RULE_CNT                                 NUMBER(10)
) NOLOGGING;

COMMENT ON TABLE  OPEOWN.TB_OPE_KRI_정보보호팀03              IS 'OPE_KRI_정보보호팀03';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_정보보호팀03.STD_DT       IS '기준일자';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_정보보호팀03.RULE_NM      IS 'RULE명';
COMMENT ON COLUMN OPEOWN.TB_OPE_KRI_정보보호팀03.RULE_CNT     IS 'RULE건수';

GRANT SELECT ON TB_OPE_KRI_정보보호팀03 TO RL_OPE_ALL;
GRANT DELETE ON TB_OPE_KRI_정보보호팀03 TO RL_OPE_ALL;
GRANT UPDATE ON TB_OPE_KRI_정보보호팀03 TO RL_OPE_ALL;
GRANT INSERT ON TB_OPE_KRI_정보보호팀03 TO RL_OPE_ALL;
GRANT SELECT ON TB_OPE_KRI_정보보호팀03 TO RL_OPE_SEL;

EXIT
