DROP PROCEDURE OPEETT.SP_INS_ETLLOG;

CREATE OR REPLACE PROCEDURE OPEETT.SP_INS_ETLLOG (
    P_TABLE_NAME IN VARCHAR2
   ,P_STD_DT  IN  VARCHAR2
   ,P_LD_CNT  IN  NUMBER
   ,P_TSK_DESC IN  VARCHAR2
)
AUTHID CURRENT_USER
AS
BEGIN
    INSERT INTO TB_OPE_KRI_ETLLOG
    VALUES
    (P_TABLE_NAME,P_STD_DT,P_LD_CNT,P_TSK_DESC,SYSDATE);
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/
GRANT EXECUTE ON OPEETT.SP_INS_ETLLOG TO RL_OPE_EXE;
GRANT EXECUTE ON OPEETT.SP_INS_ETLLOG TO PUBLIC;

EXIT
