CREATE TABLE OPEOWN.TB_OR_OM_CODE
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    INTG_GRP_C      VARCHAR2(40) NOT NULL,
    IDVDC_VAL       VARCHAR2(50) NOT NULL,
    INTG_GRP_CNM    VARCHAR2(100),
    INTG_IDVD_CNM   VARCHAR2(300),
    SORT_SQ         NUMBER(5),
    C_UYN           CHAR(1),
    MOD_IMP_YN      CHAR(1),
    DUE_DT          CHAR(8),
    RMK_CNTN        VARCHAR2(500),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OM_CODE
ADD CONSTRAINT PK_OR_OM_CODE PRIMARY KEY (GRP_ORG_C,INTG_GRP_C,IDVDC_VAL);

GRANT DELETE ON OPEOWN.TB_OR_OM_CODE TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OM_CODE TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_CODE TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OM_CODE TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_CODE TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.C_UYN IS '코드사용여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.DUE_DT IS '만기일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.IDVDC_VAL IS '개별코드값';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.INTG_GRP_C IS '통합그룹코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.INTG_GRP_CNM IS '통합그룹코드명';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.INTG_IDVD_CNM IS '통합개별코드명';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.MOD_IMP_YN IS '수정불가여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.RMK_CNTN IS '비고내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_CODE.SORT_SQ IS '정렬순서';
COMMENT ON TABLE OPEOWN.TB_OR_OM_CODE IS '공통_통합코드기본';

