CREATE TABLE OPEOWN.TB_OR_KH_RKISLT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    KRI_EVL_TGT_YN  CHAR(1),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KH_RKISLT
ADD CONSTRAINT PK_OR_KH_RKISLT PRIMARY KEY (GRP_ORG_C,BAS_YM,OPRK_RKI_ID);

GRANT DELETE ON OPEOWN.TB_OR_KH_RKISLT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KH_RKISLT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_RKISLT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KH_RKISLT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_RKISLT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KH_RKISLT.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_RKISLT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_RKISLT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_RKISLT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_RKISLT.KRI_EVL_TGT_YN IS '평가대상여부';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_RKISLT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_RKISLT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_RKISLT.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON TABLE OPEOWN.TB_OR_KH_RKISLT IS 'KRI_평가대상선정내역';

