CREATE TABLE OPEOWN.TB_OR_SH_CTEV
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    SNRO_SC         NUMBER(6) NOT NULL,
    BSN_PRSS_C      VARCHAR2(12) NOT NULL,
    OPRK_RKP_ID     VARCHAR2(10) NOT NULL,
    RK_CTL_SQNO     NUMBER(5) NOT NULL,
    BAS_YM          VARCHAR2(6),
    CTL_CNTN        VARCHAR2(800),
    CTEV_GRD_AVL    NUMBER(5,3),
    RED_CN          NUMBER(13),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_SH_CTEV
ADD CONSTRAINT PK_OR_SH_CTEV PRIMARY KEY (GRP_ORG_C,SNRO_SC,BSN_PRSS_C,OPRK_RKP_ID,RK_CTL_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_SH_CTEV TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_SH_CTEV TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_SH_CTEV TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_SH_CTEV TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_SH_CTEV TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.CTEV_GRD_AVL IS '통제평가등급평균값';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.CTL_CNTN IS '통제내용';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.OPRK_RKP_ID IS '운영리스크리스크풀ID';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.RED_CN IS '적색건수';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.RK_CTL_SQNO IS '리스크통제일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_CTEV.SNRO_SC IS '시나리오회차';
COMMENT ON TABLE OPEOWN.TB_OR_SH_CTEV IS '시나리오_통제평가내역';

