CREATE TABLE OPEOWN.TB_OR_KS_RKI_SMST
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    OPRK_RKINM      VARCHAR2(200),
    RKI_ATTR_C      CHAR(2),
    KRI_GRDNM       VARCHAR2(20),
    CFT_PLAN_YN     CHAR(1),
    KRI_LMT_DSC     CHAR(2),
    AFLCO_ORGZ_CN   NUMBER(13),
    AFLCO_TT_VAL    NUMBER(18,3),
    RKI_UNT_C       CHAR(2),
    KRI_UNTNM       VARCHAR2(20),
    GU_DRTN_RER_DSC CHAR(1),
    ACT_PLN_GRDC    CHAR(1),
    SC1_LMT_VAL     NUMBER(18,3),
    SQ2_LMT_VAL     NUMBER(18,3),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

CREATE UNIQUE INDEX OPEOWN.PK_OR_KS_RKI_SMST
ON OPEOWN.TB_OR_KS_RKI_SMST (GRP_ORG_C,OPRK_RKI_ID,BAS_YM) 
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KS_RKI_SMST
ADD CONSTRAINT PK_OR_KS_RIKRI PRIMARY KEY (GRP_ORG_C,OPRK_RKI_ID,BAS_YM)
        USING INDEX
        OPEOWN.PK_OR_KS_RKI_SMST;

GRANT DELETE ON OPEOWN.TB_OR_KS_RKI_SMST TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KS_RKI_SMST TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KS_RKI_SMST TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KS_RKI_SMST TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KS_RKI_SMST TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.ACT_PLN_GRDC IS '조치계획등급코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.AFLCO_ORGZ_CN IS '계열사조직수';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.AFLCO_TT_VAL IS '계열사합계값';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.CFT_PLAN_YN IS '대응방안입력대상';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.GU_DRTN_RER_DSC IS '순방향역방향구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.KRI_GRDNM IS '핵심리스크지표등급명';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.KRI_LMT_DSC IS '핵심리스크지표한도구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.KRI_UNTNM IS '핵심리스크지표단위명';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.OPRK_RKINM IS '운영리스크리스크지표명';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.RKI_ATTR_C IS '리스크지표속성코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.RKI_UNT_C IS '리스크지표단위코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.SC1_LMT_VAL IS '1차한도값';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_RKI_SMST.SQ2_LMT_VAL IS '2차한도값';
COMMENT ON TABLE OPEOWN.TB_OR_KS_RKI_SMST IS 'KRI_지표수준(전사)리스크지표별집계';

