CREATE TABLE OPEOWN.TB_OR_BC_RMRSK_GRD
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    RM_RSK_GRD_C    CHAR(2) NOT NULL,
    RM_RSK_GRDNM    VARCHAR2(10),
    RM_RSK_GRD_CNTN VARCHAR2(20),
    RNGE_MIN_VAL    NUMBER(5,3),
    RNGE_MAX_VAL    NUMBER(5,3),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BC_RMRSK_GRD
ADD CONSTRAINT PK_OR_BC_RMRSK_GRD PRIMARY KEY (GRP_ORG_C,RM_RSK_GRD_C);

GRANT DELETE ON OPEOWN.TB_OR_BC_RMRSK_GRD TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BC_RMRSK_GRD TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BC_RMRSK_GRD TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BC_RMRSK_GRD TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BC_RMRSK_GRD TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.RM_RSK_GRDNM IS '잔여위험등급명';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.RM_RSK_GRD_C IS '잔여위험등급코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.RM_RSK_GRD_CNTN IS '잔여위험등급내용';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.RNGE_MAX_VAL IS '범위최대값';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RMRSK_GRD.RNGE_MIN_VAL IS '범위최소값';
COMMENT ON TABLE OPEOWN.TB_OR_BC_RMRSK_GRD IS 'BCP_잔여위험등급코드';

