CREATE TABLE OPEOWN.TB_OR_FH_CPTAM
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    IDX_BAS_YM      CHAR(6),
    RET_DEC_AM      NUMBER(18,3),
    RET_DEC_FGN_AM  NUMBER(18,3),
    CMP_DEC_AM      NUMBER(18,3),
    CMP_DEC_FGN_AM  NUMBER(18,3),
    RP_DEC_AM       NUMBER(18,3),
    RP_DEC_FGN_AM   NUMBER(18,3),
    DPLN_SPD_RT     NUMBER(5,3),
    DPLN_SPD_FGN_RT NUMBER(5,3),
    INLS_FCT_AM     NUMBER(18,3),
    INLS_FCT_FGN_AM NUMBER(18,3),
    DCZ_SQNO        NUMBER(7),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_FH_CPTAM
ADD CONSTRAINT PK_OR_FH_CPTAM PRIMARY KEY (GRP_ORG_C,BAS_YM);

GRANT DELETE ON OPEOWN.TB_OR_FH_CPTAM TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_FH_CPTAM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FH_CPTAM TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_FH_CPTAM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FH_CPTAM TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.CMP_DEC_AM IS '기업이탈율원화금액';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.CMP_DEC_FGN_AM IS '기업이탈율외화금액';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.DCZ_SQNO IS '결재일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.DPLN_SPD_FGN_RT IS '예대스프레드외화';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.DPLN_SPD_RT IS '예대스프레드원화';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.IDX_BAS_YM IS '평판지수기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.INLS_FCT_AM IS '이자손익감소예상원화금액';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.INLS_FCT_FGN_AM IS '이자손익감소예상외화금액';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.RET_DEC_AM IS '소매이탈율원화금액';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.RET_DEC_FGN_AM IS '소매이탈율외화금액';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.RP_DEC_AM IS 'RP이탈율원화금액';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_CPTAM.RP_DEC_FGN_AM IS 'RP이탈율외화금액';
COMMENT ON TABLE OPEOWN.TB_OR_FH_CPTAM IS '평판_자본량정보내역';

