CREATE TABLE OPEOWN.TB_OR_CF_RPT
(
    GRP_ORG_C           CHAR(2) NOT NULL,
    BAS_YM              VARCHAR2(6) NOT NULL,
    RPT_TIT             VARCHAR2(500),
    RSLT_MNM_CPT_AMT    VARCHAR2(100),
    RSLT_SLF_CPT_RT     VARCHAR2(100),
    RSLT_IRRT_HGLM      CHAR(1),
    RSLT_LN_LMT         CHAR(1),
    RGLT_MNM_CPT_AMT    VARCHAR2(200),
    RGLT_SLF_CPT_RT     VARCHAR2(200),
    RGLT_IRRT_HGLM      VARCHAR2(200),
    RGLT_LN_LMT_AMT     VARCHAR2(200),
    LSS_OCC_CNT         VARCHAR2(50),
    LSS_OCC_AM          NUMBER(21,4),
    RCSA_PRSS_CNT       VARCHAR2(200),
    RCSA_RKP_CNT        NUMBER(7),
    RCSA_EVL_CNT        NUMBER(7),
    KRI_RED_CNT         NUMBER(7),
    KRI_YELLOW_CNT      NUMBER(7),
    KRI_GREEN_CNT       NUMBER(7),
    BCP_CNTN            VARCHAR2(2000),
    SNR_CNTN            VARCHAR2(2000),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
)
NOLOGGING;

ALTER TABLE OPEOWN.TB_OR_CF_RPT
ADD CONSTRAINT PK_OR_CF_ADM_RPT PRIMARY KEY (GRP_ORG_C,BAS_YM);

GRANT DELETE ON OPEOWN.TB_OR_CF_RPT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_CF_RPT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_CF_RPT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_CF_RPT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_CF_RPT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.BAS_YM IS '보고년월';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.BCP_CNTN IS 'BCP관련내용';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.KRI_GREEN_CNT IS 'KRI_GREEN건수';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.KRI_RED_CNT IS 'KRI_RED건수';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.KRI_YELLOW_CNT IS 'KRI_YELLOW건수';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.LSS_OCC_AM IS '손실사건_발생금액';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.LSS_OCC_CNT IS '손실사건_발생건수';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RCSA_EVL_CNT IS 'RCSA_평가건수';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RCSA_PRSS_CNT IS 'RCSA_전체프로세스수';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RCSA_RKP_CNT IS 'RCSA_전체 수';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RGLT_IRRT_HGLM IS '규제기준_이자율상한';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RGLT_LN_LMT_AMT IS '규제기준_1인당대출한도';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RGLT_MNM_CPT_AMT IS '규제기준_최소자본금';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RGLT_SLF_CPT_RT IS '규제기준_자기자본비율';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RPT_TIT IS '보고서명';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RSLT_IRRT_HGLM IS '점검결과_이자율상한';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RSLT_LN_LMT IS '점검결과_1인당대출한도';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RSLT_MNM_CPT_AMT IS '점검결과_최소자본금';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.RSLT_SLF_CPT_RT IS '점검결과_자기자본비율';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT.SNR_CNTN IS '시나리오및기타사항내용';
COMMENT ON TABLE OPEOWN.TB_OR_CF_RPT IS '해외법인_운영리스크 월보고';

