CREATE TABLE OPEOWN.TB_OR_OH_MENU_AUTH
(
    GRP_ORG_C       CHAR(2) DEFAULT NULL NOT NULL,
    AUTH_GRP_ID     VARCHAR2(3) NOT NULL,
    MENU_ID         VARCHAR2(20) NOT NULL,
    VLD_YN          CHAR(1),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OH_MENU_AUTH
ADD CONSTRAINT PK_OR_OH_MENU_AUTH PRIMARY KEY (GRP_ORG_C,AUTH_GRP_ID,MENU_ID);

GRANT DELETE ON OPEOWN.TB_OR_OH_MENU_AUTH TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OH_MENU_AUTH TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OH_MENU_AUTH TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OH_MENU_AUTH TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OH_MENU_AUTH TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.AUTH_GRP_ID IS '권한그룹ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_AUTH.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_OH_MENU_AUTH IS '공통_메뉴별권한내역';

