CREATE TABLE OPEOWN.TB_OR_GA_FNASTM_UPDTL
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    UPLOAD_SQNO     NUMBER(5) NOT NULL,
    SACCT_SQNO      NUMBER(10) NOT NULL,
    HD_INP_DSC      CHAR(2),
    ACC_TPC         CHAR(2),
    ULD_ACC_CNM     VARCHAR2(50),
    ULD_ACC_NM      VARCHAR2(100),
    LVL_NO          NUMBER(2),
    FILL_YN_DSC     CHAR(2),
    UP_ULD_ACC_CNM  VARCHAR2(50),
    UP_ULD_ACC_NM   VARCHAR2(100),
    BIZ_IX_LV1_NM   VARCHAR2(30),
    BIZ_IX_LV2_NM   VARCHAR2(30),
    MPP_EXP_RSN_DSC CHAR(2),
    HD_MNG_TGT_YN   CHAR(1),
    NOTE_CNTN       VARCHAR2(4000),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_FNASTM_UPDTL
ADD CONSTRAINT PK_OR_GA_FNASTM_UPDTL PRIMARY KEY (GRP_ORG_C,BAS_YM,UPLOAD_SQNO,SACCT_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_GA_FNASTM_UPDTL TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_FNASTM_UPDTL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_FNASTM_UPDTL TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_FNASTM_UPDTL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_FNASTM_UPDTL TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.ACC_TPC IS '계정유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.BIZ_IX_LV1_NM IS '영업지수매핑1레벨명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.BIZ_IX_LV2_NM IS '영업지수매핑2레벨명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.FILL_YN_DSC IS '기표여부구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.HD_INP_DSC IS '수기입력구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.HD_MNG_TGT_YN IS '수기관리대상여부';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.LVL_NO IS '레벨번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.MPP_EXP_RSN_DSC IS '매핑제외사유구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.NOTE_CNTN IS '비고';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.SACCT_SQNO IS '가계정일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.ULD_ACC_CNM IS '계정과목코드명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.ULD_ACC_NM IS '계정과목명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.UPLOAD_SQNO IS '업로드일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.UP_ULD_ACC_CNM IS '상위업로드계정코드명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPDTL.UP_ULD_ACC_NM IS '상위업로드계정명';
COMMENT ON TABLE OPEOWN.TB_OR_GA_FNASTM_UPDTL IS '측정_재무제표업로드상세';

