CREATE TABLE OPEOWN.TB_OR_LM_OUT_LSHP
(
    GRP_ORG_C           CHAR(2) NOT NULL,
    OUT_LSHP_AMNNO      NUMBER(9) NOT NULL,
    HPN_OCU_ORGNM       VARCHAR2(200),
    RG_BRNM             VARCHAR2(400),
    COL_METHC           CHAR(2),
    LSS_TINM            VARCHAR2(500),
    LSS_DTL_CNTN        CLOB,
    OCU_DT              CHAR(8),
    DSCV_DT             CHAR(8),
    INPDT               CHAR(8),
    CAS_TPC             VARCHAR2(8),
    HPN_TPC             VARCHAR2(8),
    EMRK_TPC            VARCHAR2(5),
    IFN_TPC             VARCHAR2(5),
    TTLS_AM             NUMBER(18,3),
    TOT_WDR_AM          NUMBER(17,2),
    GULS_AM             NUMBER(17,2),
    RMK_CNTN            VARCHAR2(500),
    RKP_HLD_YN          CHAR(1),
    OPRK_RKP_ID         VARCHAR2(10),
    ORG_SNT_OBJ_YN      CHAR(1),
    DRTR_SNT_OBJ_YN     CHAR(1),
    EMP_SNT_OBJ_YN      CHAR(1),
    SNT_CNTN            CLOB,
    SNT_ACT_DT          CHAR(8),
    TMP_YN              CHAR(1),
    ETC_OUT_RMK_CNTN    VARCHAR2(2000),
    VLD_ST_DT           CHAR(8),
    VLD_ED_DT           CHAR(8),
    VLD_YN              CHAR(1),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
)
LOB (LSS_DTL_CNTN) STORE AS SECUREFILE 
(
    STORAGE
    (
        INITIAL 4M
        NEXT 4M
    )
    CHUNK 8192
    PCTVERSION 0
)
LOB (SNT_CNTN) STORE AS SECUREFILE 
(
    STORAGE
    (
        INITIAL 4M
        NEXT 4M
    )
    CHUNK 8192
    PCTVERSION 0
);

ALTER TABLE OPEOWN.TB_OR_LM_OUT_LSHP
ADD CONSTRAINT PK_OR_LM_OUT_LSHP PRIMARY KEY (GRP_ORG_C,OUT_LSHP_AMNNO);

GRANT DELETE ON OPEOWN.TB_OR_LM_OUT_LSHP TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_LM_OUT_LSHP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LM_OUT_LSHP TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_LM_OUT_LSHP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LM_OUT_LSHP TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.CAS_TPC IS '원인유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.COL_METHC IS '수집방법코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.DRTR_SNT_OBJ_YN IS '임원제재대상여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.DSCV_DT IS '발견일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.EMP_SNT_OBJ_YN IS '직원제재대상여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.EMRK_TPC IS '이머징리스크유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.ETC_OUT_RMK_CNTN IS '기타외부비고내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.GULS_AM IS '순손실금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.HPN_OCU_ORGNM IS '사건발생기관명';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.HPN_TPC IS '사건유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.IFN_TPC IS '영향유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.INPDT IS '입력일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.LSS_DTL_CNTN IS '손실사건상세내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.LSS_TINM IS '손실사건제목명';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.OCU_DT IS '발생일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.OPRK_RKP_ID IS '운영리스크리스크풀ID';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.ORG_SNT_OBJ_YN IS '기관제재대상여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.OUT_LSHP_AMNNO IS '외부손실사건관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.RG_BRNM IS '등록사무소명';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.RKP_HLD_YN IS '리스크풀보유여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.RMK_CNTN IS '비고내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.SNT_ACT_DT IS '제재조치일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.SNT_CNTN IS '제재내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.TMP_YN IS '임시여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.TOT_WDR_AM IS '총회수금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.TTLS_AM IS '총손실금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_OUT_LSHP.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_LM_OUT_LSHP IS '손실사건_외부손실사건기본';

