CREATE TABLE OPEOWN.TB_OR_BM_UGBR_BKUP
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BSN_PRSS_C      CHAR(8) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    BAS_DT          CHAR(8) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BM_UGBR_BKUP
ADD CONSTRAINT PK_OR_BM_UGBR_BKUP PRIMARY KEY (GRP_ORG_C,BSN_PRSS_C,BRC,BAS_DT);

GRANT DELETE ON OPEOWN.TB_OR_BM_UGBR_BKUP TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BM_UGBR_BKUP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BM_UGBR_BKUP TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BM_UGBR_BKUP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BM_UGBR_BKUP TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BM_UGBR_BKUP.BAS_DT IS '기준일자';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_UGBR_BKUP.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_UGBR_BKUP.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_UGBR_BKUP.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_UGBR_BKUP.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_UGBR_BKUP.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_UGBR_BKUP.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_UGBR_BKUP.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_BM_UGBR_BKUP IS 'BCP_재해대응프로세스사용부서백업기본';

