CREATE TABLE OPEOWN.TB_OR_BC_RKFCTR
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    RSK_C           CHAR(6) NOT NULL,
    RSK_PFRNM       VARCHAR2(100),
    UP_RSK_C        CHAR(6),
    LVL_NO          NUMBER(2),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BC_RKFCTR
ADD CONSTRAINT PK_OR_BC_RKFCTR PRIMARY KEY (GRP_ORG_C,RSK_C);

GRANT DELETE ON OPEOWN.TB_OR_BC_RKFCTR TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BC_RKFCTR TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BC_RKFCTR TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BC_RKFCTR TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BC_RKFCTR TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.LVL_NO IS '레벨번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.RSK_C IS '위험코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.RSK_PFRNM IS '위험요인명';
COMMENT ON COLUMN OPEOWN.TB_OR_BC_RKFCTR.UP_RSK_C IS '상위위험코드';
COMMENT ON TABLE OPEOWN.TB_OR_BC_RKFCTR IS 'BCP_위험요소코드';

