CREATE TABLE OPEOWN.TB_OR_KH_INF
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    REL_TBLNM       VARCHAR2(100) NOT NULL,
    TBL_EXPL        VARCHAR2(4000),
    XTR_CND_SQLS    VARCHAR2(4000),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KH_INF
ADD CONSTRAINT PK_OR_KH_INF PRIMARY KEY (GRP_ORG_C,OPRK_RKI_ID,REL_TBLNM);

GRANT DELETE ON OPEOWN.TB_OR_KH_INF TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KH_INF TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_INF TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KH_INF TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_INF TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.REL_TBLNM IS '관련테이블명';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.TBL_EXPL IS '전산배치추출쿼리';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_INF.XTR_CND_SQLS IS '추출조건SQL문';
COMMENT ON TABLE OPEOWN.TB_OR_KH_INF IS 'KRI_리스크정보내역';

