CREATE TABLE OPEOWN.TB_OR_OM_ONL_TRLOG
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    TR_SQNO         NUMBER(10) NOT NULL,
    OPR_DTM         DATE,
    OPTR_ENO        VARCHAR2(10),
    IPADR           CHAR(20),
    MENU_ID         VARCHAR2(20),
    SVCID           VARCHAR2(100),
    BRC             VARCHAR2(20),
    CRUD_DSCD       VARCHAR2(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OM_ONL_TRLOG
ADD CONSTRAINT PK_OR_OM_ONL_TRLOG PRIMARY KEY (GRP_ORG_C,TR_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_OM_ONL_TRLOG TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OM_ONL_TRLOG TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_ONL_TRLOG TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OM_ONL_TRLOG TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_ONL_TRLOG TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.IPADR IS 'IP주소';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.OPR_DTM IS '조작일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.OPTR_ENO IS '조작자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.SVCID IS '서비스ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_ONL_TRLOG.TR_SQNO IS '거래일련번호';
COMMENT ON TABLE OPEOWN.TB_OR_OM_ONL_TRLOG IS '공통_온라인거래로그기본';

