CREATE TABLE OPEOWN.TB_OR_RM_NGRD
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    NFNA_IFN_C      CHAR(1) NOT NULL,
    NFNA_IFN_GRDNM  VARCHAR2(50),
    NFNA_IBI_CNTN   VARCHAR2(500),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RM_NGRD
ADD CONSTRAINT PK_OR_RM_NGRD PRIMARY KEY (GRP_ORG_C,NFNA_IFN_C);

GRANT DELETE ON OPEOWN.TB_OR_RM_NGRD TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RM_NGRD TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_NGRD TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RM_NGRD TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_NGRD TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD.NFNA_IBI_CNTN IS '영문재무영향등급명';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD.NFNA_IFN_C IS '재무영향코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD.NFNA_IFN_GRDNM IS '재무영향등급명';
COMMENT ON TABLE OPEOWN.TB_OR_RM_NGRD IS 'RCSA_재무영향등급기본';

