CREATE TABLE OPEOWN.TB_OR_GA_MSRELM
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    RGO_IN_DSC      CHAR(1) NOT NULL,
    SBDR_C          CHAR(2) NOT NULL,
    MSR_ELM_DSCD    CHAR(4) NOT NULL,
    MSR_AM          NUMBER(29,13),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_MSRELM
ADD CONSTRAINT PK_OR_GA_MSRELM PRIMARY KEY (GRP_ORG_C,BAS_YM,RGO_IN_DSC,SBDR_C,MSR_ELM_DSCD);

GRANT DELETE ON OPEOWN.TB_OR_GA_MSRELM TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_MSRELM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_MSRELM TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_MSRELM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_MSRELM TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.MSR_AM IS '산출금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.MSR_ELM_DSCD IS '산출구성요소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.RGO_IN_DSC IS '규제내부구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRELM.SBDR_C IS '자회사코드';
COMMENT ON TABLE OPEOWN.TB_OR_GA_MSRELM IS '측정_구성요소별산출';

