CREATE TABLE OPEOWN.TB_OR_KH_BRC
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KH_BRC
ADD CONSTRAINT PK_OR_KH_BRC PRIMARY KEY (GRP_ORG_C,OPRK_RKI_ID,BRC);

GRANT DELETE ON OPEOWN.TB_OR_KH_BRC TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KH_BRC TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_BRC TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KH_BRC TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_BRC TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KH_BRC.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_BRC.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_BRC.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_BRC.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_BRC.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_BRC.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_BRC.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON TABLE OPEOWN.TB_OR_KH_BRC IS 'KRI_적용사무소내역';

