CREATE TABLE OPEOWN.TB_OR_LH_LSAM
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    LSHP_AMNNO      NUMBER(9) NOT NULL,
    LSSAM_SQNO      NUMBER(5) NOT NULL,
    ACC_DSC         CHAR(1),
    LSOC_AM         NUMBER(18),
    TR_CNTN         VARCHAR2(500),
    HPN_RC_DT       CHAR(8),
    ACD_NO          NUMBER(10),
    LSS_ISR_KDC     VARCHAR2(2),
    LWS_PRG_CNTN    VARCHAR2(4000),
    LWS_HPN_NO      VARCHAR2(20),
    WDR_AM_RCP_DT   CHAR(8),
    RMK_CNTN        VARCHAR2(200),
    LSS_ACG_ACCC    VARCHAR2(20),
    BRC             VARCHAR2(20),
    TR_SQNO         NUMBER(10),
    SACCT_SQNO      NUMBER(10),
    RVPY_DSC        CHAR(1),
    CRC_CAN_DSC     CHAR(1),
    ACG_PRC_DT      CHAR(8),
    LSOC_CURC       VARCHAR2(3),
    BAS_XCRT_NVL    NUMBER(17,2),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    VLD_YN          CHAR(1),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_LH_LSAM
ADD CONSTRAINT PK_OR_LH_LSAM PRIMARY KEY (GRP_ORG_C,LSHP_AMNNO,LSSAM_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_LH_LSAM TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_LH_LSAM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LH_LSAM TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_LH_LSAM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LH_LSAM TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.ACC_DSC IS '계정구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.ACD_NO IS '사고번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.ACG_PRC_DT IS '회계처리일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.BAS_XCRT_NVL IS '기준환율수치';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.CRC_CAN_DSC IS '정정취소구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.HPN_RC_DT IS '사건접수일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LSHP_AMNNO IS '손실사건관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LSOC_AM IS '손실발생금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LSOC_CURC IS '손실발생통화코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LSSAM_SQNO IS '손실금액일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LSS_ACG_ACCC IS '손실회계계정코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LSS_ISR_KDC IS '손실보험종류코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LWS_HPN_NO IS '사건번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.LWS_PRG_CNTN IS '소송진행내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.RMK_CNTN IS '비고내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.RVPY_DSC IS '입금지급구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.SACCT_SQNO IS '가계정일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.TR_CNTN IS '거래내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.TR_SQNO IS '거래일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.VLD_YN IS '유효여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_LSAM.WDR_AM_RCP_DT IS '회수금액수령일자';
COMMENT ON TABLE OPEOWN.TB_OR_LH_LSAM IS '손실사건_손실금액내역';

