CREATE TABLE OPEOWN.TB_OR_GA_LCDET
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    RGO_IN_DSC      CHAR(1) NOT NULL,
    SBDR_C          CHAR(2) NOT NULL,
    LSHP_AMNNO      NUMBER(9) NOT NULL,
    LSSAM_SQNO      NUMBER(5) NOT NULL,
    ACC_DSC         CHAR(1),
    LSOC_AM         NUMBER(18),
    LSS_ACG_ACCC    VARCHAR2(20),
    RVPY_DSC        CHAR(1),
    ACG_PRC_DT      CHAR(8) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_LCDET
ADD CONSTRAINT PK_OR_GA_LCDET PRIMARY KEY (GRP_ORG_C,BAS_YM,RGO_IN_DSC,SBDR_C,LSHP_AMNNO,LSSAM_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_GA_LCDET TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_LCDET TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_LCDET TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_LCDET TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_LCDET TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.ACC_DSC IS '계정구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.ACG_PRC_DT IS '회계처리일자';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.LSHP_AMNNO IS '손실사건관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.LSOC_AM IS '손실발생금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.LSSAM_SQNO IS '손실금액일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.LSS_ACG_ACCC IS '손실회계계정코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.RGO_IN_DSC IS '규제내부구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.RVPY_DSC IS '입금지급구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LCDET.SBDR_C IS '자회사코드';
COMMENT ON TABLE OPEOWN.TB_OR_GA_LCDET IS '측정_LC산출손실내역상세';

