CREATE TABLE OPEOWN.TB_OR_GA_LMT_EXRAT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BASYY           CHAR(4) NOT NULL,
    RGO_IN_DSC      CHAR(1) NOT NULL,
    SBDR_C          CHAR(2) NOT NULL,
    CASE_DSC        CHAR(2) NOT NULL,
    BAS_MM          CHAR(2) NOT NULL,
    TOT_NED_OWNFDS  NUMBER(21),
    LMT_RTO         NUMBER(6,3),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_LMT_EXRAT
ADD CONSTRAINT PK_OR_GA_LMT_EXRAT PRIMARY KEY (GRP_ORG_C,BASYY,RGO_IN_DSC,SBDR_C,CASE_DSC,BAS_MM);

GRANT DELETE ON OPEOWN.TB_OR_GA_LMT_EXRAT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_LMT_EXRAT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_LMT_EXRAT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_LMT_EXRAT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_LMT_EXRAT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.BASYY IS '기준년도';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.BAS_MM IS '기준월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.CASE_DSC IS '케이스구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.LMT_RTO IS '소진율';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.RGO_IN_DSC IS '규제내부구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.SBDR_C IS '자회사코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_LMT_EXRAT.TOT_NED_OWNFDS IS '총소요자기자본';
COMMENT ON TABLE OPEOWN.TB_OR_GA_LMT_EXRAT IS '측정_한도소진율';

