CREATE TABLE OPEOWN.TB_OR_GA_FNASTM_UPLOAD
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    UPLOAD_SQNO     NUMBER(5) NOT NULL,
    APFLNM          VARCHAR2(100),
    RG_DT           CHAR(8),
    RG_ENO          VARCHAR2(10),
    VLD_YN          CHAR(1),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_FNASTM_UPLOAD
ADD CONSTRAINT PK_OR_GA_FNASTM_UPLOAD PRIMARY KEY (GRP_ORG_C,BAS_YM,UPLOAD_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_GA_FNASTM_UPLOAD TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_FNASTM_UPLOAD TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_FNASTM_UPLOAD TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_FNASTM_UPLOAD TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_FNASTM_UPLOAD TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.APFLNM IS '첨부파일명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.RG_DT IS '등록일자';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.RG_ENO IS '등록개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.UPLOAD_SQNO IS '업로드일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_UPLOAD.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_GA_FNASTM_UPLOAD IS '측정_재무제표업로드';

