CREATE TABLE OPEOWN.TB_OR_KS_BR_SMST
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    BRNM            VARCHAR2(40),
    UP_BRC          VARCHAR2(20),
    LVL_NO          NUMBER(2),
    RED_CN          NUMBER(13),
    YLW_CN          NUMBER(13),
    GREEN_CN        NUMBER(13),
    CFT_PLAN_CN     NUMBER(7),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

CREATE UNIQUE INDEX OPEOWN.PK_OR_KS_BR_SMST
ON OPEOWN.TB_OR_KS_BR_SMST (GRP_ORG_C,BRC,BAS_YM) 
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KS_BR_SMST
ADD CONSTRAINT PK_OR_KS_BRKRI PRIMARY KEY (GRP_ORG_C,BRC,BAS_YM)
        USING INDEX
        OPEOWN.PK_OR_KS_BR_SMST;

GRANT DELETE ON OPEOWN.TB_OR_KS_BR_SMST TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KS_BR_SMST TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KS_BR_SMST TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KS_BR_SMST TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KS_BR_SMST TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.BRNM IS '사무소명';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.CFT_PLAN_CN IS '대응방안건수';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.GREEN_CN IS '녹색건수';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.LVL_NO IS '레벨번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.RED_CN IS '적색건수';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.UP_BRC IS '상위사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KS_BR_SMST.YLW_CN IS '황색건수';
COMMENT ON TABLE OPEOWN.TB_OR_KS_BR_SMST IS 'KRI_사무소별집계';

