CREATE TABLE OPEOWN.TB_OR_KM_FIX_LMT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    FIX_SC1_LMT_VAL NUMBER(18,3),
    FIX_SQ2_LMT_VAL NUMBER(18,3),
    LMT_CHG_CNTN    VARCHAR2(2000),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KM_FIX_LMT
ADD CONSTRAINT PK_OR_KM_FIX_LMT PRIMARY KEY (GRP_ORG_C,OPRK_RKI_ID,BRC);

GRANT DELETE ON OPEOWN.TB_OR_KM_FIX_LMT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KM_FIX_LMT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KM_FIX_LMT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KM_FIX_LMT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KM_FIX_LMT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.FIX_SC1_LMT_VAL IS '고정1차한도값';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.FIX_SQ2_LMT_VAL IS '고정2차한도값';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.LMT_CHG_CNTN IS '한도변경내용상세';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_FIX_LMT.OPRK_RKI_ID IS '운영리스크리스크지표ID';

