CREATE TABLE OPEOWN.TB_OR_RM_FRQ
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    FRQ_GRDC        CHAR(1) NOT NULL,
    AVG_FQCN        NUMBER(7,2),
    AVG_FRQ_CNTN    VARCHAR2(255),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RM_FRQ
ADD CONSTRAINT PK_OR_RM_FRQ PRIMARY KEY (GRP_ORG_C,FRQ_GRDC);

GRANT DELETE ON OPEOWN.TB_OR_RM_FRQ TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RM_FRQ TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_FRQ TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RM_FRQ TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_FRQ TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RM_FRQ.AVG_FQCN IS '평균빈도수';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_FRQ.AVG_FRQ_CNTN IS '평균빈도내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_FRQ.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_FRQ.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_FRQ.FRQ_GRDC IS '빈도등급코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_FRQ.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_FRQ.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_FRQ.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_RM_FRQ IS 'RCSA_빈도등급기본';

