CREATE TABLE OPEOWN.TB_OR_FH_INDEX
(
    GRP_ORG_C           CHAR(2) NOT NULL,
    BAS_YM              CHAR(6) NOT NULL,
    REP_IDX             NUMBER(18,3),
    BEF_REP_IDX         NUMBER(18,3),
    IDX_INDC_RT         NUMBER(18,3),
    REP_STDD_SUM        NUMBER(18,3),
    REP_STDD_AVG        NUMBER(18,3),
    REP_STDD_STDV       NUMBER(18,3),
    BEF_REP_STDD_AVG    NUMBER(18,3),
    BEF_REP_STDD_STDV   NUMBER(18,3),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_FH_INDEX
ADD CONSTRAINT PK_OR_FH_INDEX PRIMARY KEY (GRP_ORG_C,BAS_YM);

GRANT DELETE ON OPEOWN.TB_OR_FH_INDEX TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_FH_INDEX TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FH_INDEX TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_FH_INDEX TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FH_INDEX TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.BEF_REP_IDX IS '전분기평판지수';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.BEF_REP_STDD_AVG IS '전분기평판표준화평균';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.BEF_REP_STDD_STDV IS '전분기평판표준화편차';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.IDX_INDC_RT IS '인덱스증감율';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.REP_IDX IS '당분기평판지수';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.REP_STDD_AVG IS '평판표준화평균';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.REP_STDD_STDV IS '평판표준화편차';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_INDEX.REP_STDD_SUM IS '평판표준화합계';
COMMENT ON TABLE OPEOWN.TB_OR_FH_INDEX IS '평판_INDEX산출내역';

