CREATE TABLE OPEOWN.TB_OR_SH_RCSA
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    SNRO_SC         NUMBER(6) NOT NULL,
    BSN_PRSS_C      VARCHAR2(12) NOT NULL,
    OPRK_RKP_ID     VARCHAR2(10) NOT NULL,
    RK_ISC_CNTN     VARCHAR2(4000),
    RK_EVL_GRD_AVL  NUMBER(5,3),
    RED_CN          NUMBER(13),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10),
    BAS_YM          CHAR(6) NOT NULL
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_SH_RCSA
ADD CONSTRAINT PK_OR_SH_RCSA PRIMARY KEY (GRP_ORG_C,SNRO_SC,BSN_PRSS_C,OPRK_RKP_ID);

GRANT DELETE ON OPEOWN.TB_OR_SH_RCSA TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_SH_RCSA TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_SH_RCSA TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_SH_RCSA TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_SH_RCSA TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.OPRK_RKP_ID IS '운영리스크리스크풀ID';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.RED_CN IS '적색건수';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.RK_EVL_GRD_AVL IS '리스크평가등급평균값';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.RK_ISC_CNTN IS '리스크사례내용';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RCSA.SNRO_SC IS '시나리오회차';
COMMENT ON TABLE OPEOWN.TB_OR_SH_RCSA IS '시나리오_위험평가내역';

