CREATE TABLE OPEOWN.TB_OR_SH_RSKBSN
(
    GRP_ORG_C           CHAR(2) NOT NULL,
    SNRO_SC             NUMBER(6) NOT NULL,
    BSN_PRSS_C          VARCHAR2(12) NOT NULL,
    LV1_BSN_PRSNM       VARCHAR2(200),
    LV2_BSN_PRSNM       VARCHAR2(200),
    LV3_BSN_PRSNM       VARCHAR2(200),
    LV4_BSN_PRSNM       VARCHAR2(200),
    LSOC_CN             NUMBER(6),
    KRI_OCU_CN          NUMBER(6),
    RA_OCU_CN           NUMBER(6),
    CTEV_OCU_CN         NUMBER(6),
    LS_RSK_SCR          NUMBER(9,3),
    CLC_RQR_DTM         VARCHAR2(14),
    LS_CLC_DTM          VARCHAR2(14),
    RSKDRVR_ANSS_CNTN   VARCHAR2(2000),
    CFT_PLAN_CNTN       VARCHAR2(2000),
    CFRC_OPI_CNTN       VARCHAR2(4000),
    RSK_BSN_YN          CHAR(1),
    DCZ_SQNO            NUMBER(7),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10),
    SNRO_SET            VARCHAR2(2000)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_SH_RSKBSN
ADD CONSTRAINT PK_OR_SH_RSKBSN PRIMARY KEY (GRP_ORG_C,SNRO_SC,BSN_PRSS_C);

GRANT DELETE ON OPEOWN.TB_OR_SH_RSKBSN TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_SH_RSKBSN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_SH_RSKBSN TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_SH_RSKBSN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_SH_RSKBSN TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.CFRC_OPI_CNTN IS '협의의견내용';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.CFT_PLAN_CNTN IS '대응방안내용';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.CLC_RQR_DTM IS '계산요청일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.CTEV_OCU_CN IS '통제평가발생건수';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.DCZ_SQNO IS '결재일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.KRI_OCU_CN IS 'KRI발생건수';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LSOC_CN IS '손실발생건수';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LS_CLC_DTM IS '최종계산일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LS_RSK_SCR IS '최종위험점수';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LV1_BSN_PRSNM IS '1레벨업무프로세스명';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LV2_BSN_PRSNM IS '2레벨업무프로세스명';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LV3_BSN_PRSNM IS '3레벨업무프로세스명';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.LV4_BSN_PRSNM IS '4레벨업무프로세스명';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.RA_OCU_CN IS 'RA발생건수';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.RSKDRVR_ANSS_CNTN IS '위험요인분석내용';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.RSK_BSN_YN IS '위험업무여부';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.SNRO_SC IS '시나리오회차';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_RSKBSN.SNRO_SET IS '시나리오설정';
COMMENT ON TABLE OPEOWN.TB_OR_SH_RSKBSN IS '시나리오_중요위험업무내역';

