CREATE TABLE OPEOWN.TB_OR_OC_EMRK
(
    GRP_ORG_C           CHAR(2) DEFAULT NULL NOT NULL,
    EMRK_TPC            VARCHAR2(5) NOT NULL,
    EMRK_TPNM           VARCHAR2(200),
    ENG_EMRK_TPNM       VARCHAR2(200),
    LVL_NO              NUMBER(2),
    UP_EMRK_TPC         VARCHAR2(5),
    EMRK_TP_CNTN        VARCHAR2(800),
    ENG_EMRK_TP_CNTN    VARCHAR2(800),
    VLD_ST_DT           CHAR(8),
    VLD_ED_DT           CHAR(8),
    VLD_YN              CHAR(1),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OC_EMRK
ADD CONSTRAINT PK_OR_OC_EMRK PRIMARY KEY (GRP_ORG_C,EMRK_TPC);

GRANT DELETE ON OPEOWN.TB_OR_OC_EMRK TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OC_EMRK TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OC_EMRK TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OC_EMRK TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OC_EMRK TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.EMRK_TPC IS '이머징리스크유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.EMRK_TPNM IS '이머징리스크유형명';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.EMRK_TP_CNTN IS '이머징리스크유형내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.ENG_EMRK_TPNM IS '영문이머징리스크유형명';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.ENG_EMRK_TP_CNTN IS '영문이머징리스크유형내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.LVL_NO IS '레벨번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.UP_EMRK_TPC IS '상위이머징리스크유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_EMRK.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_OC_EMRK IS '공통_이머징리스크유형코드';

