CREATE TABLE OPEOWN.TB_OR_OH_MENU_PRSS
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    MENU_ID         VARCHAR2(20) NOT NULL,
    PGID            VARCHAR2(20) NOT NULL,
    PRSS_KDC        CHAR(2) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OH_MENU_PRSS
ADD CONSTRAINT PK_OR_OH_MENU_PRSS PRIMARY KEY (GRP_ORG_C,MENU_ID,PGID,PRSS_KDC);

GRANT DELETE ON OPEOWN.TB_OR_OH_MENU_PRSS TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OH_MENU_PRSS TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OH_MENU_PRSS TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OH_MENU_PRSS TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OH_MENU_PRSS TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PRSS.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PRSS.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PRSS.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PRSS.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PRSS.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PRSS.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PRSS.PGID IS '프로그램ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PRSS.PRSS_KDC IS '프로세스종류코드';

