CREATE TABLE OPEOWN.TB_OR_FH_REL_RKI
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    REP_RKI_ID      VARCHAR2(8) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_FH_REL_RKI
ADD CONSTRAINT PK_OR_FH_REL_RKI PRIMARY KEY (GRP_ORG_C,REP_RKI_ID,OPRK_RKI_ID);

GRANT DELETE ON OPEOWN.TB_OR_FH_REL_RKI TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_FH_REL_RKI TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FH_REL_RKI TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_FH_REL_RKI TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FH_REL_RKI TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_FH_REL_RKI.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_REL_RKI.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_REL_RKI.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_REL_RKI.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_REL_RKI.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_REL_RKI.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_REL_RKI.REP_RKI_ID IS '평판리스크지표ID';
COMMENT ON TABLE OPEOWN.TB_OR_FH_REL_RKI IS '평판_관련KRI내역';

