CREATE TABLE OPEOWN.TB_OR_RM_GRD
(
    GRP_ORG_C               CHAR(2) NOT NULL,
    FNA_IFN_C               CHAR(1) NOT NULL,
    FNA_IFN_GRDNM           VARCHAR2(50),
    ENG_FNA_IFN_GRDNM       VARCHAR2(50),
    IFN_EVL_ST_NVL          NUMBER(18,3),
    IFN_EVL_ED_NVL          NUMBER(18,3),
    ENG_IFN_EVL_ST_NVL      NUMBER(18,3),
    ENG_IFN_EVL_ED_NVL      NUMBER(18,3),
    IFN_EVL_ST_BASCD        CHAR(2),
    IFN_EVL_ED_BASCD        CHAR(2),
    ENG_IFN_EVL_ST_BASCD    CHAR(2),
    ENG_IFN_EVL_ED_BASCD    CHAR(2),
    FIR_INP_DTM             DATE,
    FIR_INPMN_ENO           VARCHAR2(10),
    LSCHG_DTM               DATE,
    LS_WKR_ENO              VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RM_GRD
ADD CONSTRAINT PK_OR_RM_GRD PRIMARY KEY (GRP_ORG_C,FNA_IFN_C);

GRANT DELETE ON OPEOWN.TB_OR_RM_GRD TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RM_GRD TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_GRD TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RM_GRD TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_GRD TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.ENG_FNA_IFN_GRDNM IS '영문재무영향등급명';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.ENG_IFN_EVL_ED_BASCD IS '영문영향평가종료기준코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.ENG_IFN_EVL_ED_NVL IS '영문영향평가종료수치';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.ENG_IFN_EVL_ST_BASCD IS '영문영향평가시작기준코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.ENG_IFN_EVL_ST_NVL IS '영문영향평가시작수치';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.FNA_IFN_C IS '재무영향코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.FNA_IFN_GRDNM IS '재무영향등급명';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.IFN_EVL_ED_BASCD IS '영향평가종료기준코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.IFN_EVL_ED_NVL IS '영향평가종료수치';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.IFN_EVL_ST_BASCD IS '영향평가시작기준코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.IFN_EVL_ST_NVL IS '영향평가시작수치';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_GRD.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_RM_GRD IS 'RCSA_재무영향등급기본';

