CREATE TABLE OPEOWN.TB_OR_OC_GLACC
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    ACG_PRC_DT      CHAR(8) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    LSS_ACG_ACCC    VARCHAR2(20) NOT NULL,
    TR_SQNO         NUMBER(10) NOT NULL,
    SACCT_SQNO      NUMBER(10) NOT NULL,
    RVPY_DSC        CHAR(1) NOT NULL,
    CRC_CAN_DSC     CHAR(1) NOT NULL,
    ACC_SBJNM       VARCHAR2(100),
    ACC_AM          NUMBER(15),
    TR_CNTN         VARCHAR2(500),
    LSS_RG_STSC     CHAR(2),
    LSS_RG_RQR_STSC CHAR(2),
    LSS_RG_RQR_DT   CHAR(8),
    X_RSNCTT        VARCHAR2(2000),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OC_GLACC
ADD CONSTRAINT PK_OR_OC_GLACC PRIMARY KEY (GRP_ORG_C,ACG_PRC_DT,BRC,LSS_ACG_ACCC,TR_SQNO,SACCT_SQNO,RVPY_DSC,CRC_CAN_DSC);

GRANT DELETE ON OPEOWN.TB_OR_OC_GLACC TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OC_GLACC TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OC_GLACC TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OC_GLACC TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OC_GLACC TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.ACC_AM IS '계정금액';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.ACC_SBJNM IS '계정과목명';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.ACG_PRC_DT IS '회계처리일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.CRC_CAN_DSC IS '정정취소구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.LSS_ACG_ACCC IS '손실회계계정코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.LSS_RG_RQR_DT IS '손실등록요청일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.LSS_RG_RQR_STSC IS '손실등록요청상태코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.LSS_RG_STSC IS '손실등록상태코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.RVPY_DSC IS '입금지급구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.SACCT_SQNO IS '가계정일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.TR_CNTN IS '거래내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.TR_SQNO IS '거래일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_GLACC.X_RSNCTT IS '제외사유내용';
COMMENT ON TABLE OPEOWN.TB_OR_OC_GLACC IS '공통_GL계정기본';

