CREATE TABLE OPEOWN.TB_OR_OC_IFN
(
    GRP_ORG_C       CHAR(2) DEFAULT NULL NOT NULL,
    IFN_TPC         VARCHAR2(5) NOT NULL,
    IFN_TPNM        VARCHAR2(200),
    ENG_IFN_TPNM    VARCHAR2(200),
    LVL_NO          NUMBER(2),
    UP_IFN_TPC      VARCHAR2(5),
    IFN_TP_CNTN     VARCHAR2(800),
    ENG_IFN_TP_CNTN VARCHAR2(800),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    VLD_YN          CHAR(1),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OC_IFN
ADD CONSTRAINT PK_OR_OC_IFN PRIMARY KEY (GRP_ORG_C,IFN_TPC);

GRANT DELETE ON OPEOWN.TB_OR_OC_IFN TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OC_IFN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OC_IFN TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OC_IFN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OC_IFN TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.ENG_IFN_TPNM IS '영문영향유형명';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.ENG_IFN_TP_CNTN IS '영문영향유형내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.IFN_TPC IS '영향유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.IFN_TPNM IS '영향유형명';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.IFN_TP_CNTN IS '영향유형내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.LVL_NO IS '레벨번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.UP_IFN_TPC IS '상위영향유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OC_IFN.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_OC_IFN IS '공통_영향유형코드';

