CREATE TABLE OPEOWN.TB_OR_RH_KRK_SLT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKP_ID     VARCHAR2(10) NOT NULL,
    KRK_SLT_BASCD   CHAR(2),
    KRK_SLT_ST_DT   CHAR(8),
    KRK_SLT_ED_DT   CHAR(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RH_KRK_SLT
ADD CONSTRAINT PK_OR_RH_KRK_SLT PRIMARY KEY (GRP_ORG_C,OPRK_RKP_ID,KRK_SLT_BASCD);

GRANT DELETE ON OPEOWN.TB_OR_RH_KRK_SLT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RH_KRK_SLT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RH_KRK_SLT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RH_KRK_SLT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RH_KRK_SLT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.KRK_SLT_BASCD IS '중요리스크선정기준코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.KRK_SLT_ED_DT IS '중요리스크선정종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.KRK_SLT_ST_DT IS '중요리스크선정시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_KRK_SLT.OPRK_RKP_ID IS '운영리스크리스크풀ID';
COMMENT ON TABLE OPEOWN.TB_OR_RH_KRK_SLT IS 'RCSA_중요리스크선정내역';

