CREATE TABLE OPEOWN.TB_OR_KM_ACT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    KRI_GRDNM       VARCHAR2(20),
    CAS_DTL_CNTN    VARCHAR2(2000),
    CFT_PLAN_CNTN   VARCHAR2(2000),
    EXE_RZT_CNTN    VARCHAR2(2000),
    ACT_ST_DT       CHAR(8),
    ACT_ED_DT       CHAR(8),
    ACT_CPL_DT      CHAR(8),
    DCZ_SQNO        NUMBER(7),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KM_ACT
ADD CONSTRAINT PK_OR_KM_ACT PRIMARY KEY (GRP_ORG_C,BAS_YM,OPRK_RKI_ID,BRC);

GRANT DELETE ON OPEOWN.TB_OR_KM_ACT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KM_ACT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KM_ACT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KM_ACT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KM_ACT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.ACT_CPL_DT IS '이행완료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.ACT_ED_DT IS '기한종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.ACT_ST_DT IS '기한시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.CAS_DTL_CNTN IS '원인상세내용';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.CFT_PLAN_CNTN IS '대응방안내용';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.DCZ_SQNO IS '결재일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.EXE_RZT_CNTN IS '실행결과내용';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.KRI_GRDNM IS '핵심리스크지표등급명';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KM_ACT.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON TABLE OPEOWN.TB_OR_KM_ACT IS 'KRI_조치계획기본';

