CREATE TABLE OPEOWN.TB_OR_BH_PRCD_BSN
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    PRCD_BRC        VARCHAR2(20) NOT NULL,
    BSN_PRSS_C      VARCHAR2(12) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BH_PRCD_BSN
ADD CONSTRAINT PK_OR_BH_PRCD_BSN PRIMARY KEY (GRP_ORG_C,BAS_YM,PRCD_BRC,BSN_PRSS_C,BRC);

GRANT DELETE ON OPEOWN.TB_OR_BH_PRCD_BSN TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BH_PRCD_BSN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_PRCD_BSN TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BH_PRCD_BSN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_PRCD_BSN TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_PRCD_BSN.PRCD_BRC IS '선행사무소코드';
COMMENT ON TABLE OPEOWN.TB_OR_BH_PRCD_BSN IS 'BCP_선행업무내역';

