CREATE TABLE OPEOWN.TB_OR_OM_EMP
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    ENO             VARCHAR2(10) NOT NULL,
    BRC             VARCHAR2(20),
    TMS_BRC         VARCHAR2(20),
    CHRG_EMPNM      VARCHAR2(50),
    HDOF_RTR_DSC    CHAR(1),
    PZCC            VARCHAR2(20),
    OFT_C           VARCHAR2(20),
    TEAM_CD         VARCHAR2(8),
    ADOP_DT         CHAR(8),
    APNT_DT         CHAR(8),
    RTR_DT          CHAR(8),
    OFFC_TEL_CNTN   VARCHAR2(40),
    GNAF_CHRR_YN    CHAR(1),
    OPRK_AMN_YN     CHAR(1),
    LS_CONN_DTM     DATE,
    USR_IPADR       CHAR(20),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OM_EMP
ADD CONSTRAINT PK_OR_OM_EMP PRIMARY KEY (GRP_ORG_C,ENO);

GRANT DELETE ON OPEOWN.TB_OR_OM_EMP TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OM_EMP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_EMP TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OM_EMP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_EMP TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.ADOP_DT IS '채용일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.APNT_DT IS '부임일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.CHRG_EMPNM IS '담당직원명';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.ENO IS '개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.GNAF_CHRR_YN IS '서무담당자여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.HDOF_RTR_DSC IS '재직퇴직구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.LS_CONN_DTM IS '최종접속일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.OFFC_TEL_CNTN IS '사무실전화내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.OFT_C IS '직명코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.OPRK_AMN_YN IS '운영리스크관리자여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.PZCC IS '직급코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.RTR_DT IS '퇴직일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.TEAM_CD IS '팀코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.TMS_BRC IS '전송사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMP.USR_IPADR IS '사용자IP주소';
COMMENT ON TABLE OPEOWN.TB_OR_OM_EMP IS '공통_직원기본';

