CREATE TABLE OPEOWN.TB_OR_GA_INLMT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BASYY           CHAR(4) NOT NULL,
    RGO_IN_DSC      CHAR(1) NOT NULL,
    SBDR_C          CHAR(2) NOT NULL,
    UPLOAD_SQNO     NUMBER(5),
    COIC_CASE_DSC   CHAR(2),
    MNG_PLN_RTO     NUMBER(5,3),
    LSS_AM          NUMBER(21),
    RZT_YN          CHAR(1),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_INLMT
ADD CONSTRAINT PK_OR_GA_INLMT PRIMARY KEY (GRP_ORG_C,BASYY,RGO_IN_DSC,SBDR_C);

GRANT DELETE ON OPEOWN.TB_OR_GA_INLMT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_INLMT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_INLMT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_INLMT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_INLMT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.BASYY IS '기준년도';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.COIC_CASE_DSC IS '선택케이스구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.LSS_AM IS '손실금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.MNG_PLN_RTO IS '경영계획비율';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.RGO_IN_DSC IS '규제내부구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.RZT_YN IS '최종확정여부';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.SBDR_C IS '자회사코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT.UPLOAD_SQNO IS '업로드일련번호';
COMMENT ON TABLE OPEOWN.TB_OR_GA_INLMT IS '측정_내부한도설정';

