CREATE TABLE OPEOWN.TB_OR_RM_NGRD_CNTN
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    NFNA_IFN_C      CHAR(1) NOT NULL,
    NFNA_CNTN_C     CHAR(2) NOT NULL,
    NFNA_CNTN       VARCHAR2(1000),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RM_NGRD_CNTN
ADD CONSTRAINT PK_OR_RM_NGRD_CNTN PRIMARY KEY (GRP_ORG_C,NFNA_IFN_C,NFNA_CNTN_C);

GRANT DELETE ON OPEOWN.TB_OR_RM_NGRD_CNTN TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RM_NGRD_CNTN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_NGRD_CNTN TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RM_NGRD_CNTN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_NGRD_CNTN TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD_CNTN.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD_CNTN.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD_CNTN.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD_CNTN.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD_CNTN.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD_CNTN.NFNA_CNTN IS '영문영향평가종료기준코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD_CNTN.NFNA_CNTN_C IS '리스크평가회차';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_NGRD_CNTN.NFNA_IFN_C IS '재무영향코드';
COMMENT ON TABLE OPEOWN.TB_OR_RM_NGRD_CNTN IS 'RCSA_재무영향등급월말';

