CREATE TABLE OPEOWN.TB_OR_GA_INLMT_RZT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BASYY           CHAR(4) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    YM_C            CHAR(1) NOT NULL,
    BNK_BIC         NUMBER(32,13),
    BNK_LC          NUMBER(32,13),
    MYN_BIC         NUMBER(32,13),
    MYN_LC          NUMBER(32,13),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_INLMT_RZT
ADD CONSTRAINT PK_OR_GA_INLMT_RZT PRIMARY KEY (GRP_ORG_C,BASYY,BAS_YM,YM_C);

GRANT DELETE ON OPEOWN.TB_OR_GA_INLMT_RZT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_INLMT_RZT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_INLMT_RZT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_INLMT_RZT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_INLMT_RZT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.BASYY IS '기준년도';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.BNK_BIC IS '은행BIC';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.BNK_LC IS '은행LC';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.MYN_BIC IS '미얀마BIC';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.MYN_LC IS '미얀마LC';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_RZT.YM_C IS '년도분기구분';
COMMENT ON TABLE OPEOWN.TB_OR_GA_INLMT_RZT IS '측정_내부한도산출상세';

