CREATE TABLE OPEOWN.TB_OR_GA_MSRRZT_SUB
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    RGO_IN_DSC      CHAR(1) NOT NULL,
    SBDR_C          CHAR(2) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_MSRRZT_SUB
ADD CONSTRAINT PK_OR_GA_MSRRZT_SUB PRIMARY KEY (GRP_ORG_C,BAS_YM,RGO_IN_DSC,SBDR_C);

GRANT DELETE ON OPEOWN.TB_OR_GA_MSRRZT_SUB TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_MSRRZT_SUB TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_MSRRZT_SUB TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_MSRRZT_SUB TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_MSRRZT_SUB TO RL_OPE_SEL;


