CREATE TABLE OPEOWN.TB_OR_RH_REL_LSS
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKP_ID     VARCHAR2(10) NOT NULL,
    LSHP_AMNNO      NUMBER(9) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RH_REL_LSS
ADD CONSTRAINT PK_OR_RH_REL_LSS PRIMARY KEY (GRP_ORG_C,OPRK_RKP_ID,LSHP_AMNNO);

GRANT DELETE ON OPEOWN.TB_OR_RH_REL_LSS TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RH_REL_LSS TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RH_REL_LSS TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RH_REL_LSS TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RH_REL_LSS TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RH_REL_LSS.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_REL_LSS.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_REL_LSS.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_REL_LSS.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_REL_LSS.LSHP_AMNNO IS '손실사건관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_REL_LSS.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RH_REL_LSS.OPRK_RKP_ID IS '운영리스크리스크풀ID';
COMMENT ON TABLE OPEOWN.TB_OR_RH_REL_LSS IS 'RCSA_관련손실내역';

