CREATE TABLE OPEOWN.TB_OR_OM_MENU
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    MENU_ID         VARCHAR2(20) NOT NULL,
    PAGE_MNNM       VARCHAR2(100),
    UP_MENU_ID      VARCHAR2(20),
    MENU_EXPL_CNTN  VARCHAR2(255),
    DTL_MENU_URLNM  VARCHAR2(500),
    SORT_SQ_VAL     NUMBER(2),
    HPS_URLNM       VARCHAR2(500),
    BSC_MENU_YN     CHAR(1),
    HOFC_DEPT_YN    CHAR(1),
    BIZ_HOFC_YN     CHAR(1),
    BIZO_YN         CHAR(1),
    FR_DEPT_YN      CHAR(1),
    OPRK_DEPT_YN    CHAR(1),
    BCP_DEPT_YN     CHAR(1),
    VLD_YN          CHAR(1),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OM_MENU
ADD CONSTRAINT PK_OR_OM_MENU PRIMARY KEY (GRP_ORG_C,MENU_ID);

GRANT DELETE ON OPEOWN.TB_OR_OM_MENU TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OM_MENU TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_MENU TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OM_MENU TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_MENU TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.BCP_DEPT_YN IS 'BCP부서여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.BIZO_YN IS '영업점여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.BIZ_HOFC_YN IS '영업본부여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.BSC_MENU_YN IS '기본메뉴여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.DTL_MENU_URLNM IS '상세메뉴URL명';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.FR_DEPT_YN IS '해외부서여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.HOFC_DEPT_YN IS '본부부서여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.HPS_URLNM IS '도움말URL명';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.MENU_EXPL_CNTN IS '메뉴설명내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.OPRK_DEPT_YN IS '운영리스크부서여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.PAGE_MNNM IS '페이지메뉴명';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.SORT_SQ_VAL IS '정렬순서값';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.UP_MENU_ID IS '상위메뉴ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_MENU.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_OM_MENU IS '공통_메뉴기본';

