CREATE TABLE OPEOWN.TB_OR_SH_KRIRED
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    SNRO_SC         NUMBER(6) NOT NULL,
    BSN_PRSS_C      VARCHAR2(12) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    OPRK_RKINM      VARCHAR2(200),
    KRI_MM_AVL      NUMBER(18,3),
    RED_OCU_CN      NUMBER(7),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_SH_KRIRED
ADD CONSTRAINT PK_OR_SH_KRIRED PRIMARY KEY (GRP_ORG_C,SNRO_SC,BSN_PRSS_C,OPRK_RKI_ID);

GRANT DELETE ON OPEOWN.TB_OR_SH_KRIRED TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_SH_KRIRED TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_SH_KRIRED TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_SH_KRIRED TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_SH_KRIRED TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.KRI_MM_AVL IS 'KRI월평균값';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.OPRK_RKINM IS '운영리스크리스크지표명';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.RED_OCU_CN IS '적색발생건수';
COMMENT ON COLUMN OPEOWN.TB_OR_SH_KRIRED.SNRO_SC IS '시나리오회차';
COMMENT ON TABLE OPEOWN.TB_OR_SH_KRIRED IS '시나리오_KRIRED발생내역';

