CREATE TABLE OPEOWN.TB_OR_GA_CISSTS_SMLT
(
    GRP_ORG_C           CHAR(2) NOT NULL,
    BASYY               CHAR(4) NOT NULL,
    CIS_STS_DSC         CHAR(2) NOT NULL,
    CIS_STS_FGS         NUMBER(7,2),
    INT_LEAS_DVD_AM     NUMBER(18,3),
    SVC_CST_AM          NUMBER(21),
    FNC_TRAM            NUMBER(18,3),
    BIZ_IX_FCTR_VAL     NUMBER(18,3),
    LSS_FCTR_AM         NUMBER(18,3),
    IN_LSS_MLTPLR_AM    NUMBER(18,3),
    TOT_NED_OWNFDS      NUMBER(18),
    OPRK_ASET_AM        NUMBER(18,3),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_CISSTS_SMLT
ADD CONSTRAINT PK_OR_GA_CISSTS_SMLT PRIMARY KEY (GRP_ORG_C,BASYY,CIS_STS_DSC);

GRANT DELETE ON OPEOWN.TB_OR_GA_CISSTS_SMLT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_CISSTS_SMLT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_CISSTS_SMLT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_CISSTS_SMLT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_CISSTS_SMLT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.BASYY IS '기준년도';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.BIZ_IX_FCTR_VAL IS '영업지수요소값';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.CIS_STS_DSC IS '위기상황구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.CIS_STS_FGS IS '위기상황계수';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.FNC_TRAM IS '금융거래금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.INT_LEAS_DVD_AM IS '이자리스배당금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.IN_LSS_MLTPLR_AM IS '내부손실승수금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.LSS_FCTR_AM IS '손실요소금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.OPRK_ASET_AM IS '운영리스크자산금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.SVC_CST_AM IS '서비스비용금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_CISSTS_SMLT.TOT_NED_OWNFDS IS '총소요자기자본';
COMMENT ON TABLE OPEOWN.TB_OR_GA_CISSTS_SMLT IS '측정_위기상황별시뮬레이션내역';

