CREATE TABLE OPEOWN.TB_OR_GA_INLMT_CASE
(
    GRP_ORG_C               CHAR(2) NOT NULL,
    BASYY                   CHAR(4) NOT NULL,
    RGO_IN_DSC              CHAR(1) NOT NULL,
    SBDR_C                  CHAR(2) NOT NULL,
    CASE_DSC                CHAR(2) NOT NULL,
    EST_BUIX_AM             NUMBER(21),
    EST_LSS_AM              NUMBER(21),
    BUIX_LMT_AM             NUMBER(21),
    LSX_LMT_AM              NUMBER(21),
    IN_LSS_MLTPLR_VAL       NUMBER(5,4),
    TOT_NED_OWNFDS_LMT_AM   NUMBER(21),
    FIR_INP_DTM             DATE,
    FIR_INPMN_ENO           VARCHAR2(10),
    LSCHG_DTM               DATE,
    LS_WKR_ENO              VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_INLMT_CASE
ADD CONSTRAINT PK_OR_GA_INLMT_CASE PRIMARY KEY (GRP_ORG_C,BASYY,RGO_IN_DSC,SBDR_C,CASE_DSC);

GRANT DELETE ON OPEOWN.TB_OR_GA_INLMT_CASE TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_INLMT_CASE TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_INLMT_CASE TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_INLMT_CASE TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_INLMT_CASE TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.BASYY IS '기준년도';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.BUIX_LMT_AM IS '영업지수요소한도금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.CASE_DSC IS '케이스구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.EST_BUIX_AM IS '추정영업지수요소금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.IN_LSS_MLTPLR_VAL IS '내부손실승수값';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.LSX_LMT_AM IS '손실요소한도금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.RGO_IN_DSC IS '규제내부구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.SBDR_C IS '자회사코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_INLMT_CASE.TOT_NED_OWNFDS_LMT_AM IS '총소요자기자본한도금액';
COMMENT ON TABLE OPEOWN.TB_OR_GA_INLMT_CASE IS '측정_내부한도케이스';

