CREATE TABLE OPEOWN.TB_OR_GA_MSRACCMM
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    ACC_SBJ_CNM     VARCHAR2(50) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    ACC_SBJNM       VARCHAR2(100),
    ACC_TPC         CHAR(2),
    UP_ACC_SBJ_CNM  VARCHAR2(30),
    LVL_NO          NUMBER(2),
    LV2_BIZ_IX_C    CHAR(4),
    FILL_YN_DSC     CHAR(2),
    MPP_BAS_CNTN    VARCHAR2(4000),
    REV_OPN_CNTN    VARCHAR2(4000),
    NOTE_CNTN       VARCHAR2(4000),
    SORT_SQ         NUMBER(5),
    VLD_YN          CHAR(1),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_MSRACCMM
ADD CONSTRAINT PK_OR_GA_MSRACCMM PRIMARY KEY (GRP_ORG_C,ACC_SBJ_CNM,BAS_YM);

GRANT DELETE ON OPEOWN.TB_OR_GA_MSRACCMM TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_MSRACCMM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_MSRACCMM TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_MSRACCMM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_MSRACCMM TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.ACC_SBJNM IS '계정과목명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.ACC_SBJ_CNM IS '계정과목코드명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.ACC_TPC IS '계정유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.FILL_YN_DSC IS '기표여부구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.LV2_BIZ_IX_C IS '영업지수코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.LVL_NO IS '레벨번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.MPP_BAS_CNTN IS '매핑근거';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.NOTE_CNTN IS '비고';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.REV_OPN_CNTN IS '검토의견';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.SORT_SQ IS '정렬순서';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.UP_ACC_SBJ_CNM IS '상위계정과목코드명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_MSRACCMM.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_GA_MSRACCMM IS '측정_측정계정월말';

