CREATE TABLE OPEOWN.TB_OR_OH_EMAIL_DPAMN
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    EMAIL_SQNO      NUMBER(13) NOT NULL,
    RMRENO          VARCHAR2(10) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OH_EMAIL_DPAMN
ADD CONSTRAINT PK_OR_OH_EMAIL_DPAMN PRIMARY KEY (GRP_ORG_C,EMAIL_SQNO,RMRENO);

GRANT DELETE ON OPEOWN.TB_OR_OH_EMAIL_DPAMN TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OH_EMAIL_DPAMN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OH_EMAIL_DPAMN TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OH_EMAIL_DPAMN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OH_EMAIL_DPAMN TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OH_EMAIL_DPAMN.EMAIL_SQNO IS '이메일일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_EMAIL_DPAMN.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_EMAIL_DPAMN.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_EMAIL_DPAMN.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_EMAIL_DPAMN.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_EMAIL_DPAMN.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_EMAIL_DPAMN.RMRENO IS '수신자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_OH_EMAIL_DPAMN IS '공통_이메일수신자내역';

