CREATE TABLE OPEOWN.TB_OR_RM_RPT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    RPT_DSC         CHAR(1) NOT NULL,
    RPT_SQNO        NUMBER(10) NOT NULL,
    RPT_TINM        VARCHAR2(500),
    RPT_CNTN        VARCHAR2(4000),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RM_RPT
ADD CONSTRAINT PK_OR_RM_RPT PRIMARY KEY (GRP_ORG_C,RPT_DSC,RPT_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_RM_RPT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RM_RPT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_RPT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RM_RPT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_RPT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.RPT_CNTN IS '보고서내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.RPT_DSC IS '보고서구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.RPT_SQNO IS '보고서일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RPT.RPT_TINM IS '보고서제목명';
COMMENT ON TABLE OPEOWN.TB_OR_RM_RPT IS 'RCSA_디지털비대면리스크 보고서 기본';

