CREATE TABLE OPEOWN.TB_OR_BM_SSPIFN
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BCP_IFN_DSC     CHAR(2) NOT NULL,
    BCP_IFN_DSNM    VARCHAR2(200),
    BCP_IFN_DS_CNTN VARCHAR2(2000),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BM_SSPIFN
ADD CONSTRAINT PK_OR_BM_SSPIFN PRIMARY KEY (GRP_ORG_C,BCP_IFN_DSC);

GRANT DELETE ON OPEOWN.TB_OR_BM_SSPIFN TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BM_SSPIFN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BM_SSPIFN TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BM_SSPIFN TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BM_SSPIFN TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BM_SSPIFN.BCP_IFN_DSC IS 'BCP영향구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_SSPIFN.BCP_IFN_DSNM IS 'BCP영향구분명';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_SSPIFN.BCP_IFN_DS_CNTN IS 'BCP영향구분내용';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_SSPIFN.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_SSPIFN.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_SSPIFN.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_SSPIFN.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_SSPIFN.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_BM_SSPIFN IS 'BCP_업무중단영향기본';

