CREATE TABLE OPEOWN.TB_OR_OM_GRPORG
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    GRP_ORGNM       VARCHAR2(50),
    ORG_ABBR        VARCHAR2(50),
    SYS_UYN         CHAR(1),
    MSR_OBJ_YN      CHAR(1),
    MAJ_AFLCO_YN    CHAR(1),
    STP_DSC         CHAR(1),
    EMAIL_UYN       CHAR(1),
    PRTO_SQ         NUMBER(7),
    NO1_HCNT        VARCHAR2(200),
    NO2_HCNT        VARCHAR2(200),
    NO3_HCNT        VARCHAR2(200),
    NO4_HCNT        VARCHAR2(200),
    NO5_HCNT        VARCHAR2(200),
    NO6_HCNT        VARCHAR2(200),
    NO7_HCNT        VARCHAR2(200),
    NO8_HCNT        VARCHAR2(200),
    NO9_HCNT        VARCHAR2(200),
    NO10_HCNT       VARCHAR2(200),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OM_GRPORG
ADD CONSTRAINT PK_OR_OM_GRPORG PRIMARY KEY (GRP_ORG_C);

GRANT DELETE ON OPEOWN.TB_OR_OM_GRPORG TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OM_GRPORG TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_GRPORG TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OM_GRPORG TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_GRPORG TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.EMAIL_UYN IS '이메일사용여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.GRP_ORGNM IS '그룹기관명';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.MAJ_AFLCO_YN IS '주요계열사여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.MSR_OBJ_YN IS '측정대상여부';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO10_HCNT IS '10번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO1_HCNT IS '1번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO2_HCNT IS '2번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO3_HCNT IS '3번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO4_HCNT IS '4번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO5_HCNT IS '5번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO6_HCNT IS '6번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO7_HCNT IS '7번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO8_HCNT IS '8번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.NO9_HCNT IS '9번항목내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.ORG_ABBR IS '기관약칭명';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.PRTO_SQ IS '출력순서';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.STP_DSC IS '단계구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_GRPORG.SYS_UYN IS '시스템사용여부';
COMMENT ON TABLE OPEOWN.TB_OR_OM_GRPORG IS '공통_그룹기관기본';

