CREATE TABLE OPEOWN.TB_OR_RS_KRK
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          NUMBER(6) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    OPRK_RKP_ID     VARCHAR2(10) NOT NULL,
    BSN_PRSS_C      VARCHAR2(12),
    HPN_TPNM        VARCHAR2(200),
    ENG_HPN_TPNM    VARCHAR2(200),
    RK_ISC_CNTN     VARCHAR2(4000),
    ENG_RK_ISC_CNTN VARCHAR2(4000),
    VLR_PERS        NUMBER(7),
    FRQ_EVL_C       CHAR(1),
    IFN_EVL_C       CHAR(1),
    CTEV_GRD_C      CHAR(1),
    BF_SC_OBJ_YN    CHAR(1),
    ANW_RK_YN       CHAR(1),
    RK_GD1_RTO      NUMBER(6,3),
    RK_GD2_RTO      NUMBER(6,3),
    RK_GD3_RTO      NUMBER(6,3),
    RK_GD4_RTO      NUMBER(6,3),
    CAS_DTL_CNTN    VARCHAR2(2000),
    CFT_PLAN_CNTN   VARCHAR2(2000),
    DCZ_SQNO        NUMBER(7),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RS_KRK
ADD CONSTRAINT PK_OR_RS_KRK PRIMARY KEY (GRP_ORG_C,BAS_YM,BRC,OPRK_RKP_ID);

GRANT DELETE ON OPEOWN.TB_OR_RS_KRK TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RS_KRK TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RS_KRK TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RS_KRK TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RS_KRK TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.ANW_RK_YN IS '신규리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.BAS_YM IS '리스크평가회차';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.BF_SC_OBJ_YN IS '이전회차대상여부';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.CAS_DTL_CNTN IS '원인상세내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.CFT_PLAN_CNTN IS '대응방안내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.CTEV_GRD_C IS '통제평가등급코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.DCZ_SQNO IS '결재일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.ENG_HPN_TPNM IS '영문사건유형명';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.ENG_RK_ISC_CNTN IS '영문리스크사례내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.FRQ_EVL_C IS '빈도평가코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.HPN_TPNM IS '사건유형명';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.IFN_EVL_C IS '영향평가코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.OPRK_RKP_ID IS '운영리스크리스크풀ID';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.RK_GD1_RTO IS '리스크1급비율';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.RK_GD2_RTO IS '리스크2급비율';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.RK_GD3_RTO IS '리스크3급비율';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.RK_GD4_RTO IS '리스크4급비율';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.RK_ISC_CNTN IS '리스크사례내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RS_KRK.VLR_PERS IS '평가자인원수';
COMMENT ON TABLE OPEOWN.TB_OR_RS_KRK IS 'RCSA_중점관리대상리스크집계';

