CREATE TABLE OPEOWN.TB_OR_KH_LMT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    SC1_LMT_VAL     NUMBER(18,3),
    SQ2_LMT_VAL     NUMBER(18,3),
    RYR1_AVL        NUMBER(18,3),
    RYR1_SDVA       NUMBER(18,3),
    RYR1_MAX_VAL    NUMBER(18,3),
    RYR1_MIN_VAL    NUMBER(18,3),
    BFYY_AVL        NUMBER(18,3),
    BFYY_SDVA       NUMBER(18,3),
    BFYY_MAX_VAL    NUMBER(18,3),
    BFYY_MIN_VAL    NUMBER(18,3),
    BMM_SC1_MAX_TRH NUMBER(18,3),
    BMM_SQ2_MAX_TRH NUMBER(18,3),
    LMT_CHG_CNTN    VARCHAR2(2000),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KH_LMT
ADD CONSTRAINT PK_OR_KH_LMT PRIMARY KEY (GRP_ORG_C,BRC,BAS_YM,OPRK_RKI_ID);

GRANT DELETE ON OPEOWN.TB_OR_KH_LMT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KH_LMT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_LMT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KH_LMT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_LMT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.BFYY_AVL IS '전년도평균값';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.BFYY_MAX_VAL IS '전년도최대값';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.BFYY_MIN_VAL IS '전년도최소값';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.BFYY_SDVA IS '전년도표준편차';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.BMM_SC1_MAX_TRH IS '전월1차상한임계치';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.BMM_SQ2_MAX_TRH IS '전월2차상한임계치';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.LMT_CHG_CNTN IS '한도변경내용상세';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.RYR1_AVL IS '최근1년평균값';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.RYR1_MAX_VAL IS '최근1년최대값';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.RYR1_MIN_VAL IS '최근1년최소값';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.RYR1_SDVA IS '최근1년표준편차';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.SC1_LMT_VAL IS '1차한도값';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_LMT.SQ2_LMT_VAL IS '2차한도값';
COMMENT ON TABLE OPEOWN.TB_OR_KH_LMT IS 'KRI_한도내역';

