CREATE TABLE OPEOWN.TB_OR_KH_HDNG
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKI_ID     VARCHAR2(20) NOT NULL,
    REL_TBLNM       VARCHAR2(100) NOT NULL,
    RK_HDNG_NO      NUMBER(2) NOT NULL,
    CLMN_LOGLNM     VARCHAR2(500),
    CLMN_PHNM       VARCHAR2(50),
    CLMN_MRK_CFNM   VARCHAR2(128),
    CLMN_EXPL_CNTN  VARCHAR2(500),
    DEPT_CNF_YN     CHAR(1),
    AMN_ORGZ_YN     CHAR(1),
    PSN_KEY_YN      CHAR(1),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_KH_HDNG
ADD CONSTRAINT PK_OR_KH_HDNG PRIMARY KEY (GRP_ORG_C,OPRK_RKI_ID,REL_TBLNM,RK_HDNG_NO);

GRANT DELETE ON OPEOWN.TB_OR_KH_HDNG TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_KH_HDNG TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_HDNG TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_KH_HDNG TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_KH_HDNG TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.AMN_ORGZ_YN IS '관리조직여부';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.CLMN_EXPL_CNTN IS '컬럼설명내용';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.CLMN_LOGLNM IS '컬럼논리명';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.CLMN_MRK_CFNM IS '컬럼표시분류명';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.CLMN_PHNM IS '컬럼물리명';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.DEPT_CNF_YN IS '부서공개여부';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.OPRK_RKI_ID IS '운영리스크리스크지표ID';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.PSN_KEY_YN IS '개인화사번여부';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.REL_TBLNM IS '관련테이블명';
COMMENT ON COLUMN OPEOWN.TB_OR_KH_HDNG.RK_HDNG_NO IS '리스크항목번호';
COMMENT ON TABLE OPEOWN.TB_OR_KH_HDNG IS 'KRI_리스크정보항목내역';

