CREATE TABLE OPEOWN.TB_OR_OH_MENU_PGM
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    MENU_ID         VARCHAR2(20) NOT NULL,
    PGID            VARCHAR2(20) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OH_MENU_PGM
ADD CONSTRAINT PK_OR_OH_MENU_PGM PRIMARY KEY (GRP_ORG_C,MENU_ID,PGID);

GRANT DELETE ON OPEOWN.TB_OR_OH_MENU_PGM TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OH_MENU_PGM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OH_MENU_PGM TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OH_MENU_PGM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OH_MENU_PGM TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PGM.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PGM.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PGM.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PGM.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PGM.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PGM.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OH_MENU_PGM.PGID IS '프로그램ID';
COMMENT ON TABLE OPEOWN.TB_OR_OH_MENU_PGM IS '공통_메뉴프로그램';

