DROP TABLE OPEOWN.TB_OR_LM_LSHP;
CREATE TABLE OPEOWN.TB_OR_LM_LSHP
(
    GRP_ORG_C           CHAR(2) NOT NULL,
    LSHP_AMNNO          NUMBER(9) NOT NULL,
    COMN_LSHP_AMNNO     NUMBER(9),
    OCU_RGN_C           CHAR(6),
    HPN_OCU_NATCD       CHAR(2),
    OCU_BRC             VARCHAR2(20),
    OCU_BRNM            VARCHAR2(200),
    RPRR_ENO            VARCHAR2(10),
    TMP_RG_BRC          CHAR(6),
    RPT_BRC             VARCHAR2(20),
    BND_AMN_BRC         VARCHAR2(20),
    BND_AMN_BRNM        VARCHAR2(40),
    LSS_TINM            VARCHAR2(500),
    OCU_DEPT_DTL_CNTN   CLOB,
    AMN_DEPT_DTL_CNTN   VARCHAR2(4000),
    OPRK_AMN_DTL_CNTN   VARCHAR2(4000),
    OCU_DT              CHAR(8),
    DSCV_DT             CHAR(8),
    HUR_AMNNO           VARCHAR2(100),
    LSHP_FORM_C         CHAR(2),
    LSHP_STSC           CHAR(2),
    AMN_BRC             VARCHAR2(20),
    OPRK_HAM_XPC_AM     NUMBER(18,3),
    LSS_CST_AM          NUMBER(18,3),
    OPRK_ISR_WDR_AM     NUMBER(18,3),
    LWS_CST_AM          NUMBER(18,3),
    LWS_WDR_AM          NUMBER(18,3),
    ETC_CST_AM          NUMBER(18,3),
    OPRK_ETC_WDR_AM     NUMBER(18,3),
    TTLS_AM             NUMBER(18,3),
    TOT_WDR_AM          NUMBER(17,2),
    GULS_AM             NUMBER(17,2),
    MKRK_YN             CHAR(1),
    CRRK_YN             CHAR(1),
    RWA_YN              CHAR(1),
    STRK_YN             CHAR(1),
    FMRK_YN             CHAR(1),
    LGRK_YN             CHAR(1),
    EXC_YN              CHAR(1),
    LSOC_CHAN_CNTN      VARCHAR2(50),
    LSHP_REL_WRSNM      VARCHAR2(50),
    ISR_RQS_YN          CHAR(1),
    DCZ_SQNO            NUMBER(7),
    TRF_BRK_SQNO        NUMBER(9),
    LWS_YN              CHAR(1),
    LWSJDG_DSC          CHAR(1),
    LWS_TMNT_YN         CHAR(1),
    LWS_RZT_C           CHAR(1),
    ILG_BND_REL_YN      CHAR(1),
    LWS_LG_AM           NUMBER(18,3),
    LWS_HP_NO           VARCHAR2(20),
    LWS_CURT_NM         VARCHAR2(50),
    RWA_UNQ_NO          VARCHAR2(200),
    VLD_ST_DT           CHAR(8),
    VLD_ED_DT           CHAR(8),
    VLD_YN              CHAR(1),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
)
LOB (OCU_DEPT_DTL_CNTN) STORE AS SECUREFILE 
(
    STORAGE
    (
        INITIAL 4M
        NEXT 4M
    )
    CHUNK 8192
    PCTVERSION 0
);

ALTER TABLE OPEOWN.TB_OR_LM_LSHP
ADD CONSTRAINT PK_OR_LM_LSHP PRIMARY KEY (GRP_ORG_C,LSHP_AMNNO);

GRANT DELETE ON OPEOWN.TB_OR_LM_LSHP TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_LM_LSHP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LM_LSHP TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_LM_LSHP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LM_LSHP TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.AMN_BRC IS '관리사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.AMN_DEPT_DTL_CNTN IS '관리부서상세내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.BND_AMN_BRC IS '채권관리사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.BND_AMN_BRNM IS '사무소명';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.COMN_LSHP_AMNNO IS '공통손실사건관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.CRRK_YN IS '신용리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.DCZ_SQNO IS '결재일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.DSCV_DT IS '발견일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.ETC_CST_AM IS '기타비용금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.EXC_YN IS '배제대상여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.FMRK_YN IS '평판리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.GULS_AM IS '순손실금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.HPN_OCU_NATCD IS '사건발생국가코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.HUR_AMNNO IS '인사관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.ILG_BND_REL_YN IS '부실채권관련여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.ISR_RQS_YN IS '보험청구여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LGRK_YN IS '법률리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LSHP_AMNNO IS '손실사건관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LSHP_FORM_C IS '손실사건형태코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LSHP_REL_WRSNM IS '손실사건관련상품명';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LSHP_STSC IS '손실사건상태코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LSOC_CHAN_CNTN IS '손실발생채널내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LSS_CST_AM IS '손실비용금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LSS_TINM IS '손실제목명';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWSJDG_DSC IS '소송심급구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWS_CST_AM IS '소송비용금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWS_CURT_NM IS '소송관할법원';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWS_HP_NO IS '소송사건번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWS_LG_AM IS '소송가액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWS_RZT_C IS '소송결과코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWS_TMNT_YN IS '소송종결여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWS_WDR_AM IS '소송회수금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.LWS_YN IS '소송여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.MKRK_YN IS '시장리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OCU_BRC IS '발생사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OCU_BRNM IS '사무소명';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OCU_DEPT_DTL_CNTN IS '발생부서상세내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OCU_DT IS '발생일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OCU_RGN_C IS '발생지역코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OPRK_AMN_DTL_CNTN IS '운영리스크관리자상세내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OPRK_ETC_WDR_AM IS '운영리스크기타회수금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OPRK_HAM_XPC_AM IS '운영리스크피해예상금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.OPRK_ISR_WDR_AM IS '운영리스크보험회수금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.RPRR_ENO IS '보고자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.RPT_BRC IS '보고사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.RWA_UNQ_NO IS 'RWA고유번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.RWA_YN IS '위험가중자산여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.STRK_YN IS '전략리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.TMP_RG_BRC IS '임시등록사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.TOT_WDR_AM IS '총회수금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.TRF_BRK_SQNO IS '이관일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.TTLS_AM IS '총손실금액';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LM_LSHP.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_LM_LSHP IS '손실사건_손실사건기본';

