CREATE TABLE OPEOWN.TB_OR_OM_EMAIL
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    EMAIL_DSC       CHAR(4) NOT NULL,
    BSN_LCLC        CHAR(2),
    ETR_EMAIL_CNTN  VARCHAR2(4000),
    RMK_CNTN        VARCHAR2(200),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OM_EMAIL
ADD CONSTRAINT PK_OR_OM_EMAIL PRIMARY KEY (GRP_ORG_C,EMAIL_DSC);

GRANT DELETE ON OPEOWN.TB_OR_OM_EMAIL TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OM_EMAIL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_EMAIL TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OM_EMAIL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_EMAIL TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.BSN_LCLC IS '업무대분류코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.EMAIL_DSC IS '이메일구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.ETR_EMAIL_CNTN IS '수탁이메일내용';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_EMAIL.RMK_CNTN IS '비고내용';
COMMENT ON TABLE OPEOWN.TB_OR_OM_EMAIL IS '공통_이메일기본';

