CREATE TABLE OPEOWN.TB_OR_OM_OEA_BKUP
(
    GRP_ORG_C       CHAR(2) DEFAULT NULL NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    ENO             VARCHAR2(10) NOT NULL,
    AUTH_GRP_ID     VARCHAR2(3) NOT NULL,
    BAS_DT          CHAR(8) NOT NULL,
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OM_OEA_BKUP
ADD CONSTRAINT PK_OR_OM_OEA_BKUP PRIMARY KEY (GRP_ORG_C,BRC,ENO,AUTH_GRP_ID,BAS_DT);

GRANT DELETE ON OPEOWN.TB_OR_OM_OEA_BKUP TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OM_OEA_BKUP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_OEA_BKUP TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OM_OEA_BKUP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_OEA_BKUP TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.AUTH_GRP_ID IS '권한그룹ID';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.BAS_DT IS '기준일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.ENO IS '개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_OEA_BKUP.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_OM_OEA_BKUP IS '공통_조직별직원별권한백업기본';

