CREATE TABLE OPEOWN.TB_OR_BM_BIAEVL
(
    GRP_ORG_C           CHAR(2) NOT NULL,
    BAS_YM              CHAR(6) NOT NULL,
    BSN_PRSS_C          VARCHAR2(12) NOT NULL,
    BRC                 VARCHAR2(20) NOT NULL,
    BSN_TP_IPTD_VAL     NUMBER(5,3),
    BSN_SSP_IFN_VAL     NUMBER(5,3),
    MAX_PMSS_SSP_PRDC   CHAR(2),
    OBT_RCVR_PTM_C      CHAR(2),
    QSN_RG_YN           CHAR(1),
    FIR_OBT_RCVR_HR_C   CHAR(14),
    OBT_RCVR_HR_C       CHAR(2),
    VLR_ENO             VARCHAR2(10),
    DCZ_SQNO            NUMBER(7),
    BIA_EVL_PRG_STSC    CHAR(2),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BM_BIAEVL
ADD CONSTRAINT PK_OR_BM_BIAEVL PRIMARY KEY (GRP_ORG_C,BAS_YM,BSN_PRSS_C,BRC);

GRANT DELETE ON OPEOWN.TB_OR_BM_BIAEVL TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BM_BIAEVL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BM_BIAEVL TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BM_BIAEVL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BM_BIAEVL TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.BIA_EVL_PRG_STSC IS 'BIA평가진행상태코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.BSN_SSP_IFN_VAL IS '업무중단영향값';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.BSN_TP_IPTD_VAL IS '업무유형중요도값';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.DCZ_SQNO IS '결재일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.FIR_OBT_RCVR_HR_C IS '최초목표복구시간코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.MAX_PMSS_SSP_PRDC IS '최대허용중단기간코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.OBT_RCVR_HR_C IS '목표복구시간코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.OBT_RCVR_PTM_C IS '목표복구시점코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.QSN_RG_YN IS '설문등록여부';
COMMENT ON COLUMN OPEOWN.TB_OR_BM_BIAEVL.VLR_ENO IS '평가자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_BM_BIAEVL IS 'BCP_BIA평가기본';

