CREATE TABLE OPEOWN.TB_OR_GA_MSRRZT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    UPLOAD_SQNO     NUMBER(5),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_MSRRZT
ADD CONSTRAINT PK_OR_GA_MSRRZT PRIMARY KEY (GRP_ORG_C,BAS_YM);

GRANT DELETE ON OPEOWN.TB_OR_GA_MSRRZT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_MSRRZT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_MSRRZT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_MSRRZT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_MSRRZT TO RL_OPE_SEL;


