CREATE TABLE OPEOWN.TB_OR_BH_IPTINF
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    DSQNO           NUMBER(5) NOT NULL,
    BSN_PRSS_C      VARCHAR2(12) NOT NULL,
    BRC             VARCHAR2(20) NOT NULL,
    IPT_INFNM       VARCHAR2(100),
    IPT_INF_FORM_C  CHAR(2),
    STRG_LOCNM      VARCHAR2(100),
    BKUP_YN         CHAR(1),
    BKUP_FORM_C     CHAR(2),
    BKUP_FQC        VARCHAR2(2),
    PLCNM           VARCHAR2(60),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BH_IPTINF
ADD CONSTRAINT PK_OR_BH_IPTINF PRIMARY KEY (GRP_ORG_C,BAS_YM,DSQNO,BSN_PRSS_C,BRC);

GRANT DELETE ON OPEOWN.TB_OR_BH_IPTINF TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BH_IPTINF TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_IPTINF TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BH_IPTINF TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_IPTINF TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.BKUP_FORM_C IS '백업형태코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.BKUP_FQC IS '백업주기코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.BKUP_YN IS '백업여부';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.BRC IS '사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.DSQNO IS '상세일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.IPT_INFNM IS '중요정보명';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.IPT_INF_FORM_C IS '중요정보형태코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.PLCNM IS '장소명';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_IPTINF.STRG_LOCNM IS '저장위치명';
COMMENT ON TABLE OPEOWN.TB_OR_BH_IPTINF IS '측정_내부한도설정결과';

