CREATE TABLE OPEOWN.TB_OR_OM_HLDY
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    HLDY_DT         CHAR(8) NOT NULL,
    OPRK_DOW_DSC    CHAR(1),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_OM_HLDY
ADD CONSTRAINT PK_OR_OM_HLDY PRIMARY KEY (GRP_ORG_C,HLDY_DT);

GRANT DELETE ON OPEOWN.TB_OR_OM_HLDY TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_OM_HLDY TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_HLDY TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_OM_HLDY TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_OM_HLDY TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_OM_HLDY.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_HLDY.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_HLDY.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_HLDY.HLDY_DT IS '휴일일자';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_HLDY.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_HLDY.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_OM_HLDY.OPRK_DOW_DSC IS '운영리스크요일구분코드';
COMMENT ON TABLE OPEOWN.TB_OR_OM_HLDY IS '공통_휴일기본';

