CREATE TABLE OPEOWN.TB_OR_BH_BSNTP_WVAL
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    BCP_BSN_TPC     CHAR(2) NOT NULL,
    BSN_TP_WVAL_RTO NUMBER(5,3),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BH_BSNTP_WVAL
ADD CONSTRAINT PK_OR_BH_BSNTP_WVAL PRIMARY KEY (GRP_ORG_C,BAS_YM,BCP_BSN_TPC);

GRANT DELETE ON OPEOWN.TB_OR_BH_BSNTP_WVAL TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BH_BSNTP_WVAL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_BSNTP_WVAL TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BH_BSNTP_WVAL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_BSNTP_WVAL TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BH_BSNTP_WVAL.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_BSNTP_WVAL.BCP_BSN_TPC IS 'BCP업무유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_BSNTP_WVAL.BSN_TP_WVAL_RTO IS '업무유형가중치비율';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_BSNTP_WVAL.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_BSNTP_WVAL.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_BSNTP_WVAL.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_BSNTP_WVAL.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_BSNTP_WVAL.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_BH_BSNTP_WVAL IS 'BCP_업무유형중요도가중치내역';

