CREATE TABLE OPEOWN.TB_OR_RM_RKP
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKP_ID     VARCHAR2(10) NOT NULL,
    BSN_PRSS_C      VARCHAR2(12),
    HPN_TPC         VARCHAR2(8),
    CAS_TPC         VARCHAR2(8),
    IFN_TPC         VARCHAR2(5),
    EMRK_TPC        VARCHAR2(5),
    RKP_DIGITAL_YN  CHAR(1),
    RKP_NFTF_YN     CHAR(1),
    RK_ISC_CNTN     VARCHAR2(4000),
    ENG_RK_ISC_CNTN VARCHAR2(4000),
    RPT_FQ_DSC      VARCHAR2(2),
    RKP_TPC         CHAR(2),
    KRK_YN          CHAR(1),
    APL_AFLCO_DSC   CHAR(2),
    VLD_YN          CHAR(1),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RM_RKP
ADD CONSTRAINT PK_OR_RM_RKP PRIMARY KEY (GRP_ORG_C,OPRK_RKP_ID);

GRANT DELETE ON OPEOWN.TB_OR_RM_RKP TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RM_RKP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_RKP TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RM_RKP TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RM_RKP TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.APL_AFLCO_DSC IS '적용계열사구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.CAS_TPC IS '원인유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.EMRK_TPC IS '이머징리스크유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.ENG_RK_ISC_CNTN IS '영문리스크사례내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.HPN_TPC IS '사건유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.IFN_TPC IS '영향유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.KRK_YN IS '중요리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.OPRK_RKP_ID IS '운영리스크리스크풀ID';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.RKP_DIGITAL_YN IS '디지털리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.RKP_NFTF_YN IS '비대면RP여부';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.RKP_TPC IS '리스크풀유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.RK_ISC_CNTN IS '리스크사례내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.RPT_FQ_DSC IS '보고주기구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_RM_RKP.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_RM_RKP IS 'RCSA_리스크풀기본';

