CREATE TABLE OPEOWN.TB_OR_BH_NATV_RA
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    RSK_C           CHAR(6) NOT NULL,
    NATV_RSK_HDNG_C CHAR(2) NOT NULL,
    NATV_RSK_DTLC   CHAR(2),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BH_NATV_RA
ADD CONSTRAINT PK_OR_BH_NATV_RA PRIMARY KEY (GRP_ORG_C,BAS_YM,RSK_C,NATV_RSK_HDNG_C);

GRANT DELETE ON OPEOWN.TB_OR_BH_NATV_RA TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BH_NATV_RA TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_NATV_RA TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BH_NATV_RA TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_NATV_RA TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.NATV_RSK_DTLC IS '고유위험상세코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.NATV_RSK_HDNG_C IS '고유위험항목코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NATV_RA.RSK_C IS '위험코드';
COMMENT ON TABLE OPEOWN.TB_OR_BH_NATV_RA IS 'BCP_고유위험평가내역';

