CREATE TABLE OPEOWN.TB_OR_RN_RKPMM
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    OPRK_RKP_ID     VARCHAR2(10) NOT NULL,
    BAS_YM          CHAR(6),
    BSN_PRSS_C      VARCHAR2(12),
    HPN_TPC         VARCHAR2(8),
    CAS_TPC         VARCHAR2(8),
    IFN_TPC         VARCHAR2(5),
    EMRK_TPC        VARCHAR2(5),
    RKP_DIGITAL_YN  CHAR(1),
    RKP_NFTF_YN     CHAR(1),
    RK_ISC_CNTN     VARCHAR2(4000),
    ENG_RK_ISC_CNTN VARCHAR2(4000),
    RPT_FQ_DSC      VARCHAR2(2),
    RKP_TPC         CHAR(2),
    KRK_YN          CHAR(1),
    APL_AFLCO_DSC   CHAR(2),
    VLD_YN          CHAR(1),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_RN_RKPMM
ADD CONSTRAINT PK_OR_RN_RKPMM PRIMARY KEY (GRP_ORG_C,OPRK_RKP_ID,BAS_YM);

GRANT DELETE ON OPEOWN.TB_OR_RN_RKPMM TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_RN_RKPMM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RN_RKPMM TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_RN_RKPMM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_RN_RKPMM TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.APL_AFLCO_DSC IS '적용계열사구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.BSN_PRSS_C IS '업무프로세스코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.CAS_TPC IS '원인유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.EMRK_TPC IS '이머징리스크유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.ENG_RK_ISC_CNTN IS '영문리스크사례내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.HPN_TPC IS '사건유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.IFN_TPC IS '영향유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.KRK_YN IS '중요리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.OPRK_RKP_ID IS '운영리스크리스크풀ID';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.RKP_DIGITAL_YN IS '디지털리스크여부';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.RKP_NFTF_YN IS '비대면RP여부';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.RKP_TPC IS '리스크풀유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.RK_ISC_CNTN IS '리스크사례내용';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.RPT_FQ_DSC IS '보고주기구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_RN_RKPMM.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_RN_RKPMM IS 'RCSA_리스크풀기본월말';

