CREATE TABLE OPEOWN.TB_OR_GA_UP_ACCAM
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    UPLOAD_SQNO     NUMBER(5) NOT NULL,
    SACCT_SQNO      NUMBER(10) NOT NULL,
    RGO_IN_DSC      CHAR(1) NOT NULL,
    SBDR_C          CHAR(2) NOT NULL,
    ACC_AM          NUMBER(21),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_UP_ACCAM
ADD CONSTRAINT PK_OR_GA_UP_ACCAM PRIMARY KEY (GRP_ORG_C,BAS_YM,UPLOAD_SQNO,SACCT_SQNO,RGO_IN_DSC,SBDR_C);

GRANT DELETE ON OPEOWN.TB_OR_GA_UP_ACCAM TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_UP_ACCAM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_UP_ACCAM TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_UP_ACCAM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_UP_ACCAM TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.ACC_AM IS '계정금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.RGO_IN_DSC IS '규제내부구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.SACCT_SQNO IS '가계정일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.SBDR_C IS '자회사코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_UP_ACCAM.UPLOAD_SQNO IS '업로드일련번호';
COMMENT ON TABLE OPEOWN.TB_OR_GA_UP_ACCAM IS '측정_업로드계정금액';

