CREATE TABLE OPEOWN.TB_OR_FH_NVL
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    REP_RKI_ID      VARCHAR2(8) NOT NULL,
    REP_KRI_NVL     NUMBER(18,3),
    INPMN_ENO       VARCHAR2(10),
    INPDT           CHAR(8),
    DCZ_SQNO        NUMBER(7),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_FH_NVL
ADD CONSTRAINT PK_OR_FH_NVL PRIMARY KEY (GRP_ORG_C,BAS_YM,REP_RKI_ID);

GRANT DELETE ON OPEOWN.TB_OR_FH_NVL TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_FH_NVL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FH_NVL TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_FH_NVL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FH_NVL TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.DCZ_SQNO IS '결재일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.INPDT IS '입력일자';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.INPMN_ENO IS '입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.REP_KRI_NVL IS '핵심리스크지표수치';
COMMENT ON COLUMN OPEOWN.TB_OR_FH_NVL.REP_RKI_ID IS '평판리스크지표ID';
COMMENT ON TABLE OPEOWN.TB_OR_FH_NVL IS '평판_값내역';

