CREATE TABLE OPEOWN.TB_OR_LH_TRF
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    LSHP_AMNNO      NUMBER(9) NOT NULL,
    TRF_BRK_SQNO    NUMBER(9) NOT NULL,
    BF_BRC          VARCHAR2(20),
    NOW_BRC         VARCHAR2(20),
    RGMN_ENO        VARCHAR2(10),
    TRFRG_DT        CHAR(8),
    TRF_APVMN_ENO   VARCHAR2(10),
    TRF_APV_DT      CHAR(8),
    TRF_CNTN        VARCHAR2(200),
    TRF_PRG_STSC    CHAR(2),
    RTN_CNTN        VARCHAR2(500),
    DCZ_OBJR_ENO    VARCHAR2(10),
    DCZ_RMK_C       CHAR(2),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_LH_TRF
ADD CONSTRAINT PK_OR_LH_TRF PRIMARY KEY (GRP_ORG_C,LSHP_AMNNO,TRF_BRK_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_LH_TRF TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_LH_TRF TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LH_TRF TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_LH_TRF TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LH_TRF TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.BF_BRC IS '이전사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.DCZ_OBJR_ENO IS '결재대상자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.DCZ_RMK_C IS '결재비고코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.LSHP_AMNNO IS '손실사건관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.NOW_BRC IS '현재사무소코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.RGMN_ENO IS '등록자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.RTN_CNTN IS '반려내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.TRFRG_DT IS '이관등록일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.TRF_APVMN_ENO IS '이관승인자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.TRF_APV_DT IS '이관승인일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.TRF_BRK_SQNO IS '이관일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.TRF_CNTN IS '이관내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_TRF.TRF_PRG_STSC IS '이관진행상태코드';
COMMENT ON TABLE OPEOWN.TB_OR_LH_TRF IS '손실사건_손실이관내역';

