CREATE TABLE OPEOWN.TB_OR_GA_FNASTM_DTL
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          CHAR(6) NOT NULL,
    UPLOAD_SQNO     NUMBER(5) NOT NULL,
    ACC_SBJ_CNM     VARCHAR2(50) NOT NULL,
    SACCT_SQNO      NUMBER(10) NOT NULL,
    ACC_TPC         CHAR(2),
    ACC_SBJNM       VARCHAR2(100),
    LVL_NO          NUMBER(2),
    UP_ACC_SBJ_CNM  VARCHAR2(50),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_FNASTM_DTL
ADD CONSTRAINT PK_OR_GA_FNASTM_DTL PRIMARY KEY (GRP_ORG_C,BAS_YM,UPLOAD_SQNO,ACC_SBJ_CNM);

GRANT DELETE ON OPEOWN.TB_OR_GA_FNASTM_DTL TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_FNASTM_DTL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_FNASTM_DTL TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_FNASTM_DTL TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_FNASTM_DTL TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.ACC_SBJNM IS '계정과목명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.ACC_SBJ_CNM IS '계정과목코드명';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.ACC_TPC IS '계정유형코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.LVL_NO IS '레벨번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.SACCT_SQNO IS '가계정일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.UPLOAD_SQNO IS '업로드일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_FNASTM_DTL.UP_ACC_SBJ_CNM IS '상위계정과목코드명';
COMMENT ON TABLE OPEOWN.TB_OR_GA_FNASTM_DTL IS '측정_재무제표상세';

