CREATE TABLE OPEOWN.TB_OR_FM_REPRKI
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    REP_RKI_ID      VARCHAR2(8) NOT NULL,
    REP_RKINM       VARCHAR2(200),
    REP_TYP_DSCD    CHAR(2),
    IDX_FML_CNTN    VARCHAR2(1000),
    RPT_FQ_DSC      VARCHAR2(2),
    SUP_BRC         VARCHAR2(20),
    COM_COL_PSB_YN  CHAR(1),
    VLD_YN          CHAR(1),
    VLD_ST_DT       CHAR(8),
    VLD_ED_DT       CHAR(8),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_FM_REPRKI
ADD CONSTRAINT PK_OR_FM_REPRKI PRIMARY KEY (GRP_ORG_C,REP_RKI_ID);

GRANT DELETE ON OPEOWN.TB_OR_FM_REPRKI TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_FM_REPRKI TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FM_REPRKI TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_FM_REPRKI TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_FM_REPRKI TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.COM_COL_PSB_YN IS '전산수집가능여부';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.IDX_FML_CNTN IS '지표산식내용';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.REP_RKINM IS '평판지표명';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.REP_RKI_ID IS '평판리스크지표ID';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.REP_TYP_DSCD IS '평판유형구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.RPT_FQ_DSC IS '보고주기구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.SUP_BRC IS '주관부서코드';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_FM_REPRKI.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_FM_REPRKI IS '평판_평판지표기본';

