CREATE TABLE OPEOWN.TB_OR_CF_ADM
(
    GRP_ORG_C       CHAR(2),
    BAS_YM          VARCHAR2(6),
    DCZ_SQNO        NUMBER(7),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
)
NOLOGGING;

ALTER TABLE OPEOWN.TB_OR_CF_ADM
ADD CONSTRAINT PK_OR_CF_ADM PRIMARY KEY (GRP_ORG_C,BAS_YM);

GRANT DELETE ON OPEOWN.TB_OR_CF_ADM TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_CF_ADM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_CF_ADM TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_CF_ADM TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_CF_ADM TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_CF_ADM.BAS_YM IS '보고년월';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_ADM.DCZ_SQNO IS '결재상태';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_ADM.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_ADM.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_ADM.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_ADM.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_ADM.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON TABLE OPEOWN.TB_OR_CF_ADM IS '해외법인_월보고서기본';

