CREATE TABLE OPEOWN.TB_OR_BH_NARK_SCR
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    NATV_RSK_HDNG_C CHAR(2) NOT NULL,
    NATV_RSK_DTLC   CHAR(2) NOT NULL,
    NATV_RSK_DTLNM  VARCHAR2(200),
    SCR             NUMBER(7),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_BH_NARK_SCR
ADD CONSTRAINT PK_OR_BH_NARK_SCR PRIMARY KEY (GRP_ORG_C,NATV_RSK_HDNG_C,NATV_RSK_DTLC);

GRANT DELETE ON OPEOWN.TB_OR_BH_NARK_SCR TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_BH_NARK_SCR TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_NARK_SCR TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_BH_NARK_SCR TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_BH_NARK_SCR TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.NATV_RSK_DTLC IS '고유위험상세코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.NATV_RSK_DTLNM IS '고유위험상세명';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.NATV_RSK_HDNG_C IS '고유위험항목코드';
COMMENT ON COLUMN OPEOWN.TB_OR_BH_NARK_SCR.SCR IS '점수';
COMMENT ON TABLE OPEOWN.TB_OR_BH_NARK_SCR IS 'BCP_고유위험점수내역';

