CREATE TABLE OPEOWN.TB_OR_LH_DCZ
(
    GRP_ORG_C           CHAR(2) NOT NULL,
    LSHP_AMNNO          NUMBER(9) NOT NULL,
    DCZ_SQNO            NUMBER(7) NOT NULL,
    DCZ_RQRMN_ENO       VARCHAR2(10),
    DCZMN_ENO           VARCHAR2(10),
    DCZ_DT              CHAR(8),
    LSHP_DCZ_STS_DSC    CHAR(2),
    RTN_YN              CHAR(1),
    RPSP_OPI_CNTN       VARCHAR2(300),
    RTN_CNTN            VARCHAR2(500),
    DCZ_OBJR_ENO        VARCHAR2(10),
    DCZ_RMK_C           CHAR(2),
    VLD_ST_DT           CHAR(8),
    VLD_ED_DT           CHAR(8),
    VLD_YN              CHAR(1),
    FIR_INP_DTM         DATE,
    FIR_INPMN_ENO       VARCHAR2(10),
    LSCHG_DTM           DATE,
    LS_WKR_ENO          VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_LH_DCZ
ADD CONSTRAINT PK_OR_LH_DCZ PRIMARY KEY (GRP_ORG_C,LSHP_AMNNO,DCZ_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_LH_DCZ TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_LH_DCZ TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LH_DCZ TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_LH_DCZ TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_LH_DCZ TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.DCZMN_ENO IS '결재자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.DCZ_DT IS '결재일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.DCZ_OBJR_ENO IS '결재대상자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.DCZ_RMK_C IS '결재비고코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.DCZ_RQRMN_ENO IS '결재요청자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.DCZ_SQNO IS '결재일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.LSHP_AMNNO IS '손실사건관리번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.LSHP_DCZ_STS_DSC IS '손실사건결재상태구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.RPSP_OPI_CNTN IS '상신의견내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.RTN_CNTN IS '결재의견내용';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.RTN_YN IS '반려여부';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.VLD_ED_DT IS '유효종료일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.VLD_ST_DT IS '유효시작일자';
COMMENT ON COLUMN OPEOWN.TB_OR_LH_DCZ.VLD_YN IS '유효여부';
COMMENT ON TABLE OPEOWN.TB_OR_LH_DCZ IS '손실사건_손실결재내역';

