CREATE TABLE OPEOWN.TB_OR_CF_RPT_FILE
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BAS_YM          VARCHAR2(6) NOT NULL,
    APFL_SQNO       NUMBER(7) NOT NULL,
    FL_PATHNM       VARCHAR2(500),
    REAL_FLNM       VARCHAR2(500),
    STRG_FLNM       VARCHAR2(500),
    FL_SIZE_VAL     NUMBER(21),
    RG_DTM          VARCHAR2(14),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_CF_RPT_FILE
ADD CONSTRAINT PK_OR_CF_RPT_FILE PRIMARY KEY (GRP_ORG_C,BAS_YM,APFL_SQNO);

GRANT DELETE ON OPEOWN.TB_OR_CF_RPT_FILE TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_CF_RPT_FILE TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_CF_RPT_FILE TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_CF_RPT_FILE TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_CF_RPT_FILE TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.APFL_SQNO IS '첨부파일일련번호';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.BAS_YM IS '기준년월';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.FL_PATHNM IS '파일경로명';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.FL_SIZE_VAL IS '파일크기값';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.REAL_FLNM IS '실제파일명';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.RG_DTM IS '등록일시';
COMMENT ON COLUMN OPEOWN.TB_OR_CF_RPT_FILE.STRG_FLNM IS '저장파일명';
COMMENT ON TABLE OPEOWN.TB_OR_CF_RPT_FILE IS '해외법인_보고서첨부파일';

