CREATE TABLE OPEOWN.TB_OR_GA_BYR_LMT
(
    GRP_ORG_C       CHAR(2) NOT NULL,
    BASYY           CHAR(4) NOT NULL,
    CIS_STS_DSC     CHAR(2),
    INT_LEAS_DVD_AM NUMBER(18,3),
    SVC_CST_AM      NUMBER(21),
    FNC_TRAM        NUMBER(18,3),
    TTLS_AM         NUMBER(18,3),
    FIR_INP_DTM     DATE,
    FIR_INPMN_ENO   VARCHAR2(10),
    LSCHG_DTM       DATE,
    LS_WKR_ENO      VARCHAR2(10)
)
TABLESPACE TS_OPE_DT001_08K
STORAGE
(
    INITIAL 4M
    NEXT 4M
);

ALTER TABLE OPEOWN.TB_OR_GA_BYR_LMT
ADD CONSTRAINT PK_OR_GA_BYR_LMT PRIMARY KEY (GRP_ORG_C,BASYY);

GRANT DELETE ON OPEOWN.TB_OR_GA_BYR_LMT TO RL_OPE_ALL;
GRANT INSERT ON OPEOWN.TB_OR_GA_BYR_LMT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_BYR_LMT TO RL_OPE_ALL;
GRANT UPDATE ON OPEOWN.TB_OR_GA_BYR_LMT TO RL_OPE_ALL;
GRANT SELECT ON OPEOWN.TB_OR_GA_BYR_LMT TO RL_OPE_SEL;

COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.BASYY IS '기준년도';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.CIS_STS_DSC IS '위기상황구분코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.FIR_INPMN_ENO IS '최초입력자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.FIR_INP_DTM IS '최초입력일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.FNC_TRAM IS '금융거래금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.GRP_ORG_C IS '그룹기관코드';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.INT_LEAS_DVD_AM IS '이자리스배당금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.LSCHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.LS_WKR_ENO IS '최종작업자개인번호';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.SVC_CST_AM IS '서비스비용금액';
COMMENT ON COLUMN OPEOWN.TB_OR_GA_BYR_LMT.TTLS_AM IS '총손실금액';
COMMENT ON TABLE OPEOWN.TB_OR_GA_BYR_LMT IS '손실사건_연간한도설정기본';

