LOAD DATA
TRUNCATE
INTO TABLE TEMP_OPE_KRI_∞®ªÁ±‚»π∆¿01
FIELDS TERMINATED BY '¢”'
TRAILING NULLCOLS
(  STD_DT
  ,EXE_NO   
  ,PTO_SNO 
  ,BRNO
  ,BR_NM              "TRIM(:BR_NM)"
  ,PTO_NO 
  ,PTO_DTT_CD_NM      "TRIM(:PTO_DTT_CD_NM)"
  ,OCC_DT    
)