LOAD DATA
TRUNCATE
INTO TABLE TEMP_OPE_KRI_외환지원팀06
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(  STD_DT
  ,ACNO
  ,BRNO
  ,BR_NM             "TRIM(:BR_NM)"
  ,CUST_NO
  ,CUST_NAME         "TRIM(:CUST_NAME)"
  ,CRCD
  ,LN_AMT
  ,LN_DT
  ,CMPL_DT
  ,USR_NO            "TRIM(:USR_NO)"
)