LOAD DATA
TRUNCATE
INTO TABLE TEMP_OPE_KRI_자금운용지원팀01
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(  STD_DT
  ,BRNO
  ,BR_NM                 "TRIM(:BR_NM)"
  ,DLN_STLM_NO          "TRIM(:DLN_STLM_NO)"
  ,EXPI_DT
  ,STLM_DT
)